### PR TITLE
[New API] : Generate Joke Api Added

### LINKED ISSUE #262: [New API] :  Generate Joke Api
### Brief Description 🤓

- I will Add for the new `Api` add in this project `Joke Api`
- please assign  me

### How will you develop it?🤩

Screenshot from 2024-06-08 07-47-24

### Deployment

No

### Select the open source program you are contributing to

Other

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) of this project.

### PR DESCRIPTION
**Pull request by sivaprasath2004**
# 🎯 Title and Issue Number -  [New API] : Generate Joke Api  #262 

Hello @dishamodi0910 ,
- I will add the New `Joke` Api .

## Demo
[Click Here :rocket: ](https://jokes-api-ochre.vercel.app/)

### Closes #262 

# 🗒️ Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x]  I have gone through `rules of when PR will get merged.` 
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have followed proper file structure.
- [x] I have gone through [CONTRIBUTING GUIDELINES.md](../blob/master/CONTRIBUTING.md).

 Thank you for contributing!❤️ 

Don't forget to show some love by ⭐ the repository!

### CODE REVIEW

**Comment by dishamodi0910** [comment]
Hey @sivaprasath2004, Thank you for creating PR! We will review it super soon. 😇❣️
As we continue to evolve and innovate, we encourage you to share your ideas, feedback, and code to help us push the boundaries of what's possible in the world of APIs🚀.
We hope you have followed [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md).
Thank you for being an essential part of our community. Together, we'll keep building amazing things!
Don’t forget to ⭐ our repository!
Happy Coding!✨
Will See you soon❣️

**Comment by sivaprasath2004** [comment]
@dishamodi0910 ,please merge it..

**Comment by sivaprasath2004** [comment]
[Screencast from 2024-06-23 18-31-34.webm](https://github.com/dishamodi0910/APIVerse/assets/121082414/028249f6-4d54-4de5-a1ed-8273fa7c9e32)

**Comment by sivaprasath2004** [comment]
@dishamodi0910 please check and merge it.. :rocket:

**Comment by dishamodi0910** [comment]
@sivaprasath2004 We're thrilled to inform you that your pull request has been successfully merged into the APIverse🚀🎁
Your hard work, dedication, and expertise have made a significant impact on our project, and we couldn't be more grateful for your contributions.😇
Your code will now be a part of our growing ecosystem, helping developers worldwide to create exceptional APIs.❣️🔥
Happy Coding! ✨
Will See you soon❣️

**Comment by sivaprasath2004** [comment]
@dishamodi0910 ,please give the `level3` lablel, because I'm `gssoc` contributor..

**Comment by sivaprasath2004** [comment]
@dishamodi0910 ,please give the `level3` lablel, because I'm `gssoc` contributor..

**Pull request merged**
