### PR TITLE
Country api

### LINKED ISSUE #321: [Existing API Name] : Country Guide  API
### Brief Description 🤓

Create a country guide app that allows the user to search for a particular country and then displays information related to the searched country. I have use 'Rest Countries API

### Provide reference!

https://restcountries.com/

### Select the open source program you are contributing to

Other

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) of this project.

### PR DESCRIPTION
**Pull request by IshuSinghSE**
# 🎯 Country Guide API #321 

### Closes #321   

# 🗒️ Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have gone through `rules of when PR will get merged.` 
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have updated the `README.md`
- [x] I have followed proper file structure.
- [x] I have gone through [CONTRIBUTING GUIDELINES.md](../blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by dishamodi0910** [comment]
Hey @IshuSinghSE, Thank you for creating PR! We will review it super soon. 😇❣️
As we continue to evolve and innovate, we encourage you to share your ideas, feedback, and code to help us push the boundaries of what's possible in the world of APIs🚀.
We hope you have followed [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md).
Thank you for being an essential part of our community. Together, we'll keep building amazing things!
Don’t forget to ⭐ our repository!
Happy Coding!✨
Will See you soon❣️

**Comment by IshuSinghSE** [comment]
Why did the PR fail? 😔

**Comment by dishamodi0910** [comment]
Hey @IshuSinghSE, We are already having such API already present in the repository, would want you to do enhancement in that, as we don't allow duplicate PR's in APIVerse, so closing that.

Already existing Country API on APIVerse : [Link](https://github.com/dishamodi0910/APIVerse/tree/master/Existing_API_Collection/CountryAPI)

**Comment by dishamodi0910** [comment]
@IshuSinghSE ,I wanted to reach out and let you know that we have decided to close your pull request.🙇

In case of any issues, you can contact us on [Discord](https://discord.gg/mv4NTzN).
Thank you! ❣️
Happy Coding! ✨
Will See you soon❣️

**Pull request closed without merging**
