### PR TITLE
Added new API Bored API

### LINKED ISSUE #74: [New API] : Adding Bored API
### Brief Description 🤓

Bored API is a versatile tool designed to provide users with random activity suggestions when they're feeling bored. With this API, users can access a wide range of activities to spark inspiration and alleviate boredom. From creative hobbies to outdoor adventures, Bored API offers something for everyone.

### How will you develop it?🤩

Define the API endpoints: Determine the endpoints needed to access the random activity suggestions. For example:

/activity: Get a random activity suggestion.
Data Source: Identify a reliable source for activity suggestions. Bored API itself provides a comprehensive dataset of various activities.

Authentication: As Bored API is free to use, no authentication might be required for accessing the endpoints.

Data Formatting: Decide on the format in which the data will be returned. JSON is commonly used for its simplicity and ease of parsing.

Development Tools: Choose appropriate development tools and programming languages for building the API. Consider using open-source frameworks and libraries to streamline development.

Implementation:

Set up the project structure.
Define routes for the API endpoints.
Implement logic to fetch random activity suggestions.
Format the data as JSON responses.
Handle errors and edge cases gracefully.
Test the API thoroughly to ensure functionality.

### Deployment

Yes

### Select the open source program you are contributing to

Other

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) of this project.

### PR DESCRIPTION
**Pull request by SougataXdev**
# 🎯 Title and Issue Number

[New API] : Adding Bored API 

### Closes #74 

# 🗒️ Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x] I have gone through the rules of when PR will get merged.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have created a helpful and easy-to-understand `README.md`.
- [x] I have followed proper file structure.
- [x] I have gone through [CONTRIBUTING GUIDELINES.md](../blob/master/CONTRIBUTING.md).

 Thank you for contributing!❤️ 

Don't forget to show some love by ⭐ the repository!

### CODE REVIEW

**Comment by dishamodi0910** [comment]
Hey @SougataXdev, Thank you for creating PR! We will review it super soon. 😇❣️
As we continue to evolve and innovate, we encourage you to share your ideas, feedback, and code to help us push the boundaries of what's possible in the world of APIs🚀.
We hope you have followed [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md).
Thank you for being an essential part of our community. Together, we'll keep building amazing things!
Don’t forget to ⭐ our repository!
Happy Coding!✨
Will See you soon❣️

**Review by dishamodi0910 — CHANGES_REQUESTED** [review]
Hello, as you are using the already existing API to get the results, please change the folder where you have put your changes. Add the Bored API folder under Existing API collection folder. 

CHANGES NEEDED : 
- FOLDER WHERE THE WORK IS PLACED NEEDS TO BE CHANGED.
- ADD SCREENSHOT OF THE OUTPUT IN PULL REQUEST

**Comment by SougataXdev** [comment]
@dishamodi0910 please review now , and let me know if there any issue or not

**Comment by dishamodi0910** [comment]
@SougataXdev, Make entry of it in the [README.md file](https://github.com/dishamodi0910/APIVerse/blob/master/Existing_API_Collection/README.md)

**Comment by SougataXdev** [comment]
@dishamodi0910 sorry for making another pull request ,  please check now and let me know if there is any issue or not

**Review by dishamodi0910 — APPROVED** [review]

**Comment by dishamodi0910** [comment]
@SougataXdev We're thrilled to inform you that your pull request has been successfully merged into the APIverse🚀🎁
Your hard work, dedication, and expertise have made a significant impact on our project, and we couldn't be more grateful for your contributions.😇
Your code will now be a part of our growing ecosystem, helping developers worldwide to create exceptional APIs.❣️🔥
Happy Coding! ✨
Will See you soon❣️

**Pull request merged**
