### PR TITLE
added video game savedata api along with readme and gitignore

### LINKED ISSUE #238: [New API] : Video game savedata API
### Brief Description 🤓

A REST API to manage savedata of any video game for cloud save functionality. (Contributing as a GSSoC 24' contributor)

### How will you develop it?🤩

1. I have already developed the API today.
2. It is developed using **Spring boot** and **MongoDB**.
3. Every savedata has a unique id provided by mongodb a username, and user email associated with the savedata.
4. The savedata is stored in JSON form so the fields of the savedata can be dnynamically chosen for any video game.

### Deployment

No

### Select the open source program you are contributing to

Other

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) of this project.

### PR DESCRIPTION
**Pull request by Stiffpixels**
# Added the Video Game Savedata API

### Closes #238 

# 🗒️ Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x]  I have gone through `rules of when PR will get merged.` 
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have followed proper file structure.
- [x] I have gone through [CONTRIBUTING GUIDELINES.md](../blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by dishamodi0910** [comment]
Hey @Stiffpixels, Thank you for creating PR! We will review it super soon. 😇❣️
As we continue to evolve and innovate, we encourage you to share your ideas, feedback, and code to help us push the boundaries of what's possible in the world of APIs🚀.
We hope you have followed [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md).
Thank you for being an essential part of our community. Together, we'll keep building amazing things!
Don’t forget to ⭐ our repository!
Happy Coding!✨
Will See you soon❣️

**Comment by Stiffpixels** [comment]
@dishamodi0910 can you please review its been 3 days.

**Comment by dishamodi0910** [comment]
@Stiffpixels Not accepting contributions in Java, so would close this PR, thank you for contribution.

**Comment by dishamodi0910** [comment]
@Stiffpixels ,I wanted to reach out and let you know that we have decided to close your pull request.🙇

In case of any issues, you can contact us on [Discord](https://discord.gg/mv4NTzN).
Thank you! ❣️
Happy Coding! ✨
Will See you soon❣️

**Pull request closed without merging**
