### PR TITLE
Implement userlocation details by using Geolocation API and Nominatim API

### LINKED ISSUE #168: [Existing API Name] : combing both geolocation api and nominatim api
### Brief Description 🤓

the Geolocation API to determine the user's current location accurately, With the help of the Nominatim API, the application identifies the user's location and retrieves detailed information such as the city, landmarks, and historical context associated with that location.

### Provide reference!

https://developer.mozilla.org/en-US/docs/Web/API/Geolocation_API
https://nominatim.org/

### Select the open source program you are contributing to

Other

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) of this project.

### PR DESCRIPTION
**Pull request by Rohitha-pudu**
#168 combining both geolocation api and nominatim api

### Closes #168 

# 🗒️ Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x]  I have gone through `rules of when PR will get merged.` 
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have followed proper file structure.
- [x] I have gone through [CONTRIBUTING GUIDELINES.md](../blob/master/CONTRIBUTING.md).

 Thank you for contributing!❤️ 

Don't forget to show some love by ⭐ the repository!

### CODE REVIEW

**Comment by dishamodi0910** [comment]
Hey @Rohitha-pudu, Thank you for creating PR! We will review it super soon. 😇❣️
As we continue to evolve and innovate, we encourage you to share your ideas, feedback, and code to help us push the boundaries of what's possible in the world of APIs🚀.
We hope you have followed [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md).
Thank you for being an essential part of our community. Together, we'll keep building amazing things!
Don’t forget to ⭐ our repository!
Happy Coding!✨
Will See you soon❣️

**Comment by dishamodi0910** [comment]
@Rohitha-pudu We're thrilled to inform you that your pull request has been successfully merged into the APIverse🚀🎁
Your hard work, dedication, and expertise have made a significant impact on our project, and we couldn't be more grateful for your contributions.😇
Your code will now be a part of our growing ecosystem, helping developers worldwide to create exceptional APIs.❣️🔥
Happy Coding! ✨
Will See you soon❣️

**Comment by Rohitha-pudu** [comment]
> @Rohitha-pudu We're thrilled to inform you that your pull request has been successfully merged into the APIverse🚀🎁 Your hard work, dedication, and expertise have made a significant impact on our project, and we couldn't be more grateful for your contributions.😇 Your code will now be a part of our growing ecosystem, helping developers worldwide to create exceptional APIs.❣️🔥 Happy Coding! ✨ Will See you soon❣️

u forgot to assign? @dishamodi0910

**Pull request merged**
