### PR TITLE
Covid 19 tracker API added

### LINKED ISSUE #201: [API Enhancement] : COVID Tacker API
### Brief Description 🤓

it will fetch covid total cases , total deaths , total active cases , total recovery by using `disease.sh` api. 

### How develop it ?

Choose Data Source: Select a COVID-19 data API like disease.sh or a government health department's API.

Set Up Environment: Create a Node.js project and install necessary packages like Express.js and Axios.

Define Endpoints: Create endpoints for /countries, /countries/:countryCode, and /global to fetch COVID-19 data.

Fetch Data: Use Axios to make HTTP requests to the chosen API and format the data for each endpoint.

Handle Errors: Implement error handling for failed requests or invalid data.

Test: Test your API endpoints using tools like Postman to ensure they return the expected data.

Document: Create documentation explaining how to use each endpoint, expected responses, and error handling.

**_Screenshots_**
Default Page : 
Screenshot 2024-06-02 101327
Based on country : 
Screenshot 2024-06-02 101400
Screenshot 2024-06-02 101443

### Select the open source program you are contributing to

Other

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) of this project.

### PR DESCRIPTION
**Pull request by Vipullakum007**
# 🎯 Title and Issue Number
COVID Tacker API #201

### Closes #201 

# 🗒️ Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x]  I have gone through `rules of when PR will get merged.` 
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have followed proper file structure.
- [x] I have gone through [CONTRIBUTING GUIDELINES.md](../blob/master/CONTRIBUTING.md).

Default Page
Screenshot 2024-06-02 101327
Based on Coutry
Screenshot 2024-06-02 101443

 Thank you for contributing!❤️ 

Don't forget to show some love by ⭐ the repository!

### CODE REVIEW

**Comment by dishamodi0910** [comment]
Hey @Vipullakum007, Thank you for creating PR! We will review it super soon. 😇❣️
As we continue to evolve and innovate, we encourage you to share your ideas, feedback, and code to help us push the boundaries of what's possible in the world of APIs🚀.
We hope you have followed [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md).
Thank you for being an essential part of our community. Together, we'll keep building amazing things!
Don’t forget to ⭐ our repository!
Happy Coding!✨
Will See you soon❣️

**Comment by dishamodi0910** [comment]
@Vipullakum007 Please squash all your commits into 1.

**Review by dinxsh — APPROVED** [review]
good job!

**Comment by dishamodi0910** [comment]
@Vipullakum007 We're thrilled to inform you that your pull request has been successfully merged into the APIverse🚀🎁
Your hard work, dedication, and expertise have made a significant impact on our project, and we couldn't be more grateful for your contributions.😇
Your code will now be a part of our growing ecosystem, helping developers worldwide to create exceptional APIs.❣️🔥
Happy Coding! ✨
Will See you soon❣️

**Pull request merged**
