### PR TITLE
Typofixes

### LINKED ISSUE #195: [Documentation Error] : A small typo in the README file.
### Brief Description 🤓

Under the heading "🚀When you can expect your PR will get accepted?"
Point 1: ✅ You should add either 1 new API or 1 existing APIafter testing the code properly. The file structure should be followed. README.md file should be present inside your folder.

There should be a space in the first point between the words API and testing

### Select the open source program you are contributing to

Other

### Code of Conduct

- [x] I follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) of this project.

### PR DESCRIPTION
**Pull request by MaryamMohamedYahya**
# 🎯 [Documentation Error] : A small typo in the README file. #195
### 1. Added spaces between words

- Between the words **API** and **after**.
- Between the words **at** and **least** in 2 places.
one

### 2. Inserted articles for sound grammar

- Added definite article '**the**' at 5 occurrences
- Added the article '**a**' at one instance.
two

### 3. Capitalized the word '_API_' twice for better readability.
three

### Closes #195

# 🗒️ Checklist:

- [] I have mentioned the issue number in my Pull Request.
- []  I have gone through `rules of when PR will get merged.` 
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have created a helpful and easy to understand `README.md`
- [] I have followed proper file structure.
- [] I have gone through [CONTRIBUTING GUIDELINES.md](../blob/master/CONTRIBUTING.md).

 Thank you for contributing!❤️ 

Don't forget to show some love by ⭐ the repository!

### CODE REVIEW

**Comment by dishamodi0910** [comment]
Hey @MaryamMohamedYahya, Thank you for creating PR! We will review it super soon. 😇❣️
As we continue to evolve and innovate, we encourage you to share your ideas, feedback, and code to help us push the boundaries of what's possible in the world of APIs🚀.
We hope you have followed [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md).
Thank you for being an essential part of our community. Together, we'll keep building amazing things!
Don’t forget to ⭐ our repository!
Happy Coding!✨
Will See you soon❣️

**Comment by Kritika30032002** [comment]
@dishamodi0910

**Comment by dishamodi0910** [comment]
@MaryamMohamedYahya We're thrilled to inform you that your pull request has been successfully merged into the APIverse🚀🎁
Your hard work, dedication, and expertise have made a significant impact on our project, and we couldn't be more grateful for your contributions.😇
Your code will now be a part of our growing ecosystem, helping developers worldwide to create exceptional APIs.❣️🔥
Happy Coding! ✨
Will See you soon❣️

**Pull request merged**
