### PR TITLE
json_placeholder api implementation added

### LINKED ISSUE #163: [Existing API Name] : JSON Placeholder API implementation
### Brief Description 🤓

this is very famous api which give large chunks of fake json data 
and i think this is very useful to most of the developers 
and anyone can use this implemenation easily in their projects

### Provide reference!

JSON PLACERHOLDER API

### Select the open source program you are contributing to

Other

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) of this project.

### PR DESCRIPTION
**Pull request by Yashgabani845**
# 🎯 Title and Issue Number

JSON placeholder API
I have implemented that way 
you can perform any of CRUD operation on JSON data
### Closes #163 

# Picture shows crud of data
Screenshot (120)

# 🗒️ Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x]  I have gone through `rules of when PR will get merged.` 
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have followed proper file structure.
- [x] I have gone through [CONTRIBUTING GUIDELINES.md](../blob/master/CONTRIBUTING.md).

 Thank you for contributing!❤️ 

Don't forget to show some love by ⭐ the repository!

### CODE REVIEW

**Comment by Yashgabani845** [comment]
@dishamodi0910  please review this PR

**Comment by dishamodi0910** [comment]
@Yashgabani845 There is typo in name of API in README.md file entry that you have done, please fix it.

**Comment by Yashgabani845** [comment]
@dishamodi0910  i have chnaged spelling and solved merge conflicts as well please review it again

**Comment by dishamodi0910** [comment]
@Yashgabani845 We're thrilled to inform you that your pull request has been successfully merged into the APIverse🚀🎁
Your hard work, dedication, and expertise have made a significant impact on our project, and we couldn't be more grateful for your contributions.😇
Your code will now be a part of our growing ecosystem, helping developers worldwide to create exceptional APIs.❣️🔥
Happy Coding! ✨
Will See you soon❣️

**Pull request merged**
