### PR TITLE
Solves issue#289

### LINKED ISSUE #289: [Existing API Name] : YouTube API Project: Video Search and Display
### Brief Description 🤓

I will use the YouTube Data API to create a simple web application that allows users to search for YouTube videos and display the results. Users will be able to enter a search term, view a list of video results, and click on a video to watch it directly on the webpage.

### Provide reference!

https://developers.google.com/youtube/v3

### Select the open source program you are contributing to

Other

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) of this project.

### PR DESCRIPTION
**Pull request by Praneeth-2602**
# 🎯 Title and Issue Number

### Closes #289 

# 🗒️ Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x]  I have gone through `rules of when PR will get merged.` 
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have followed proper file structure.
- [x] I have gone through [CONTRIBUTING GUIDELINES.md](../blob/master/CONTRIBUTING.md).

 Thank you for contributing!❤️ 

Don't forget to show some love by ⭐ the repository!

### CODE REVIEW

**Comment by dishamodi0910** [comment]
Hey @Praneeth-2602, Thank you for creating PR! We will review it super soon. 😇❣️
As we continue to evolve and innovate, we encourage you to share your ideas, feedback, and code to help us push the boundaries of what's possible in the world of APIs🚀.
We hope you have followed [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md).
Thank you for being an essential part of our community. Together, we'll keep building amazing things!
Don’t forget to ⭐ our repository!
Happy Coding!✨
Will See you soon❣️

**Comment by Praneeth-2602** [comment]
@dishamodi0910 please review this pr

**Comment by dishamodi0910** [comment]
@Praneeth-2602 I guess this won't be much useful, as if someone has youtube, why will we make something using API and search there :)

Please justify more on use case of it.

**Comment by Praneeth-2602** [comment]
Using the YouTube Data API to create a web app allows users to search for and watch YouTube videos directly on the site. It simplifies video discovery and enhances user engagement by integrating seamless browsing and viewing experiences in one platform.

**Comment by Praneeth-2602** [comment]
@dishamodi0910 Mam, please review this pr... I wanted to contribute to another issue

**Comment by Praneeth-2602** [comment]
@dishamodi0910 Mam, please review this pr... It has already been a week and a half

**Comment by Praneeth-2602** [comment]
@dishamodi0910 please review the pr. It has already been like a month

**Comment by dishamodi0910** [comment]
Hey @Praneeth-2602, mentioning my question again, just let me know like when I have youtube, which is available as web as well as app, so why will I want to use YouTube API to watch something, please mention the use case of this one with example.

**Comment by Praneeth-2602** [comment]
Certainly! Here's an overview for the integrated use case of Local Events and News Integration:

### Local Events and News Integration Overview

1. **Personalized Video Recommendations Based on User Interests:**
   - Tailors video content to user-selected interests (e.g., local news, sports, music events).
   - Continuously updates recommendations based on user interactions.

2. **Geolocation-Based Content Delivery:**
   - Uses user’s geographical location to provide relevant video content.
   - Notifies users about live events and breaking news nearby.

3. **Event-Centric Video Curation:**
   - Displays videos related to upcoming local events.
   - Offers real-time updates and live streams during events.

4. **Community News and Updates Integration:**
   - Integrates videos from local news channels and community broadcasters.
   - Categorizes news videos by topics like politics, safety, and local business.

5. **Post-Event Highlights and Recaps:**
   - Compiles highlight videos and recaps of past events.
   - Allows users to upload and share their own event experiences.

### Conclusion

CityConnect leverages the YouTube Data API to provide a rich and engaging user experience by integrating personalized video recommendations with local events and news content, ensuring users stay connected with their community and interests.

**Review by dinxsh — APPROVED** [review]
good job!

**Comment by dishamodi0910** [comment]
@Praneeth-2602 We're thrilled to inform you that your pull request has been successfully merged into the APIverse🚀🎁
Your hard work, dedication, and expertise have made a significant impact on our project, and we couldn't be more grateful for your contributions.😇
Your code will now be a part of our growing ecosystem, helping developers worldwide to create exceptional APIs.❣️🔥
Happy Coding! ✨
Will See you soon❣️

**Comment by Praneeth-2602** [comment]
@dinxsh @dishamodi0910 please give the labels

**Pull request merged**
