### PR TITLE
football api added

### LINKED ISSUE #173: [Existing API Name] :  Football Live Score and Statastics Api
### Brief Description 🤓

Football Live Score Api includes :

1. Teams and their details
2. Live Scores
3. Fixtures
4. Statatstics
5. Players any many more
but i will majorly include  fetching these 5 information in this API
and write html for that to show them

### Provide reference!

SOCCER'S API

### Select the open source program you are contributing to

Other

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) of this project.

### PR DESCRIPTION
**Pull request by Yashgabani845**
# 🎯 Title and Issue Number
This is football score API named soccers api 
 it has many endpoints i have shown implementation of few end points and fetched data and shown here
[Existing API Name] : Football Live Score and Statastics Api #173

### Closes #173 

# 🗒️ Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x]  I have gone through `rules of when PR will get merged.` 
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have followed proper file structure.
- [x] I have gone through [CONTRIBUTING GUIDELINES.md](../blob/master/CONTRIBUTING.md).

# Screenshots of working API data and View
Screenshot (171)
Screenshot (172)

 Thank you for contributing!❤️ 

Don't forget to show some love by ⭐ the repository!

### CODE REVIEW

**Comment by dishamodi0910** [comment]
Hey @Yashgabani845, Thank you for creating PR! We will review it super soon. 😇❣️
As we continue to evolve and innovate, we encourage you to share your ideas, feedback, and code to help us push the boundaries of what's possible in the world of APIs🚀.
We hope you have followed [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md).
Thank you for being an essential part of our community. Together, we'll keep building amazing things!
Don’t forget to ⭐ our repository!
Happy Coding!✨
Will See you soon❣️

**Comment by Yashgabani845** [comment]
@dishamodi0910  please review it
if everything is well,
and make sure you assign me this PR and add labels so that no conflict occure in future
thank you

**Comment by dishamodi0910** [comment]
@Yashgabani845 There are some points I need to make sure over here : 
1. You don't need to assign PR to yourself, that works only for issues. Once the issue is assigned to you, then whenever you create PR, that would be yours only, nothing sort of assignment is needed for PR.
2. I observed that recently one of your CRICKET score PR I have merged, this one seems more likely to be like that only, so didn't found more value adding as the purpose matters and both are having more or same kind of purpose of score implementation also the way it's executed is also same for both, so would like to close this PR in order to avoid redundancy in repository.

**Comment by dishamodi0910** [comment]
@Yashgabani845 ,I wanted to reach out and let you know that we have decided to close your pull request.🙇

In case of any issues, you can contact us on [Discord](https://discord.gg/mv4NTzN).
Thank you! ❣️
Happy Coding! ✨
Will See you soon❣️

**Comment by Yashgabani845** [comment]
@dishamodi0910 okay no issue about this PR
and just for calrification i have assigned it beacuse
i asked sanjay sir(project maanger) that PR should be assigned or not  then he said it should be 
so i did that and then after i self assigned  he told me that there is no need of that
sorry of inconvenience

**Pull request closed without merging**
