### PR TITLE
Added Weather API

### LINKED ISSUE #311: [New API] : Add Weather Api
### Brief Description 🤓

Adding Weather API 

### How will you develop it?🤩

Using rapiapi i will develop and Using html css 

### Deployment

No

### Select the open source program you are contributing to

Other

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) of this project.

### PR DESCRIPTION
**Pull request by Saipradyumnagoud**
# 🎯 Title and Issue Number

Added Weather API

### Closes #311 

# 🗒️ Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x]  I have gone through `rules of when PR will get merged.` 
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have followed proper file structure.
- [x] I have gone through [CONTRIBUTING GUIDELINES.md](../blob/master/CONTRIBUTING.md).

 Thank you for contributing!❤️ 

Don't forget to show some love by ⭐ the repository!

### CODE REVIEW

**Comment by dishamodi0910** [comment]
Hey @Saipradyumnagoud, Thank you for creating PR! We will review it super soon. 😇❣️
As we continue to evolve and innovate, we encourage you to share your ideas, feedback, and code to help us push the boundaries of what's possible in the world of APIs🚀.
We hope you have followed [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md).
Thank you for being an essential part of our community. Together, we'll keep building amazing things!
Don’t forget to ⭐ our repository!
Happy Coding!✨
Will See you soon❣️

**Comment by Saipradyumnagoud** [comment]
@dishamodi0910 Please Review it soon

**Comment by Saipradyumnagoud** [comment]
@dishamodi0910 It has been 2 weeks since i raised the issue and the pull request there is no review yet

**Comment by Saipradyumnagoud** [comment]
@dishamodi0910 please review the pull reqst let me know the changes

**Comment by dishamodi0910** [comment]
@Saipradyumnagoud, Please make following changes and raise the PR again, 
1. Remove the API Key. We never expose credentials, you can mention some dummy string value there like "your api key".
2. Mention in README.md file about how to generate the API key. Provide the source link.
3. As you are using some already existing API to fetch the data, so change the directory of your API to existing api collection folder. 

Once all the changes are done, please create the NEW PR.

**Comment by dishamodi0910** [comment]
@Saipradyumnagoud ,I wanted to reach out and let you know that we have decided to close your pull request.🙇

In case of any issues, you can contact us on [Discord](https://discord.gg/mv4NTzN).
Thank you! ❣️
Happy Coding! ✨
Will See you soon❣️

**Pull request closed without merging**
