### PR TITLE
Added Quizlet API

### LINKED ISSUE #362: [New API] : Quizlet API
### Brief Description 🤓

- The Quizlet API provides developers with access to Quizlet's extensive database of flashcards and study sets. 
- This API allows for the integration of Quizlet's content into applications, enabling features like creating, searching, and displaying study sets. It's useful for educators, students, and developers looking to build educational tools, enhance e-learning platforms, or create custom study aids. 
- By leveraging the API, users can streamline studying processes and create engaging educational content.

@dishamodi0910, assign me this issue under GSSOC

### How will you develop it?🤩

**Framework/Library:**

- React for building interactive user interfaces.

**Styling:**

- CSS (with frameworks like Bootstrap or Tailwind CSS) for styling.
- SCSS for more advanced styling capabilities.

**State Management:**

- Context API (for React) for managing application state.

### Deployment

None

### Select the open source program you are contributing to

Other

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) of this project.

### PR DESCRIPTION
**Pull request by sreevidya-16**
# 🎯 Title and Issue Number

[New API] : Quizlet API #362

### Closes #362<issue_no>

# 🗒️ Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x]  I have gone through `rules of when PR will get merged.` 
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have followed proper file structure.
- [x] I have gone through [CONTRIBUTING GUIDELINES.md](../blob/master/CONTRIBUTING.md).

 Thank you for contributing!❤️ 

Don't forget to show some love by ⭐ the repository! 

@dishamodi0910, view this PR

### CODE REVIEW

**Comment by dishamodi0910** [comment]
Hey @sreevidya-16, Thank you for creating PR! We will review it super soon. 😇❣️
As we continue to evolve and innovate, we encourage you to share your ideas, feedback, and code to help us push the boundaries of what's possible in the world of APIs🚀.
We hope you have followed [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md).
Thank you for being an essential part of our community. Together, we'll keep building amazing things!
Don’t forget to ⭐ our repository!
Happy Coding!✨
Will See you soon❣️

**Review by dinxsh — APPROVED** [review]
good job!

**Comment by sreevidya-16** [comment]
@dinxsh, merge this pull request into main

**Comment by dishamodi0910** [comment]
@sreevidya-16 We're thrilled to inform you that your pull request has been successfully merged into the APIverse🚀🎁
Your hard work, dedication, and expertise have made a significant impact on our project, and we couldn't be more grateful for your contributions.😇
Your code will now be a part of our growing ecosystem, helping developers worldwide to create exceptional APIs.❣️🔥
Happy Coding! ✨
Will See you soon❣️

**Pull request merged**
