### PR TITLE
[New API] : URL Shortener API Added

### LINKED ISSUE #293: [New API] : URL Shortener API
### Brief Description 🤓

- In this application was  changed to the `Long size` url to `short` size url..
- It will be worked for save the Long size url and we will search the shortsize url it can be redirect to the original `url`.

### How will you develop it?🤩

- please assign me..

### Deployment

No

### Select the open source program you are contributing to

Other

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) of this project.

### PR DESCRIPTION
**Pull request by sivaprasath2004**
Hello @dishamodi0910 ,
# 🎯 Title and Issue Number
[New API] : URL Shortener API  Added

### Video

[Screencast from 2024-06-17 20-06-50.webm](https://github.com/dishamodi0910/APIVerse/assets/121082414/efa1145e-0c5f-4e4b-87df-c0fdb5904d1c)

# 🗒️ Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x]  I have gone through `rules of when PR will get merged.` 
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have followed proper file structure.
- [x] I have gone through [CONTRIBUTING GUIDELINES.md](../blob/master/CONTRIBUTING.md).

 Thank you for contributing!❤️ 

Don't forget to show some love by ⭐ the repository!

### CODE REVIEW

**Comment by dishamodi0910** [comment]
Hey @sivaprasath2004, Thank you for creating PR! We will review it super soon. 😇❣️
As we continue to evolve and innovate, we encourage you to share your ideas, feedback, and code to help us push the boundaries of what's possible in the world of APIs🚀.
We hope you have followed [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md).
Thank you for being an essential part of our community. Together, we'll keep building amazing things!
Don’t forget to ⭐ our repository!
Happy Coding!✨
Will See you soon❣️

**Comment by dishamodi0910** [comment]
@sivaprasath2004 Please add proper README.md file in your API folder explaining about what you have done and how it be used.

**Comment by sivaprasath2004** [comment]
@dishamodi0910 i will finish it..

**Comment by sivaprasath2004** [comment]
@dishamodi0910 please merge this...

**Comment by sivaprasath2004** [comment]
@dishamodi0910  please merge this

**Comment by dishamodi0910** [comment]
@sivaprasath2004 Please explain brief about what logic you have used for generating the short url and also do you think this integration would be used when we are already having bit.ly in market :)

**Comment by sivaprasath2004** [comment]
Creating a URL shortener backend involves building a service that takes long URLs and generates shorter, more manageable URLs. 
```js
app.post('/api/shorten',())
```

1. **Shorten URL**:
   - POST request to `/api/shorten` with JSON body `{ "originalUrl": "https://www.example.com/blogs/nature-topic/edit }`
   - Response: `{ "originalUrl": "https://www.example.com/blogs/nature-topic/edit", "shortUrl": "http://localhost:5000/abc123"}`

2. **Redirect**:
   - GET request to `http://localhost:5000/abc123`
   - Should redirect to `https://www.example.com/blogs/nature-topic/edit`

**Review by dinxsh — APPROVED** [review]
good job!

**Comment by dishamodi0910** [comment]
@sivaprasath2004 We're thrilled to inform you that your pull request has been successfully merged into the APIverse🚀🎁
Your hard work, dedication, and expertise have made a significant impact on our project, and we couldn't be more grateful for your contributions.😇
Your code will now be a part of our growing ecosystem, helping developers worldwide to create exceptional APIs.❣️🔥
Happy Coding! ✨
Will See you soon❣️

**Pull request merged**
