### PR TITLE
[New API]: College_Lectures_API

### LINKED ISSUE #79: [New API] : College Lectures API
### Brief Description 🤓

This API serves as a basic system for managing college lectures. It allows users to perform CRUD (Create, Read, Update, Delete) operations on lecture resources. Each lecture resource has attributes such as title, instructor, time, and room.

### How will you develop it?🤩

- Setting Up Dependencies: The project utilizes Node.js and Express.js framework. We use body-parser middleware to parse incoming request bodies in JSON format.

- Defining Sample Data: We start by defining sample data for demonstration purposes. In a real-world scenario, this data would be stored in a database.

- Middleware Setup: We configure Express.js to use body-parser middleware to parse incoming JSON data.

- Routes: We define various routes for different CRUD operations on lectures:

       GET /lectures: Retrieves all lectures.
       GET /lectures/:id: Retrieves a specific lecture by its ID.
       POST /lectures: Creates a new lecture.
       PUT /lectures/:id: Updates an existing lecture.
       DELETE /lectures/:id: Deletes an existing lecture.

- Handlers for Routes:

       GET /lectures: Returns all lectures stored in memory.
       GET /lectures/:id: Retrieves a lecture with a specific ID.
       POST /lectures: Creates a new lecture based on the request body.
       PUT /lectures/:id: Updates the lecture with the specified ID based on the request body.
       DELETE /lectures/:id: Deletes the lecture with the specified ID.

- Error Handling: Proper error handling is implemented to handle cases where the requested resource is not found.

- Server Setup: We start the Express server and listen for incoming HTTP requests on a specified port.

### Deployment

No

### Select the open source program you are contributing to

Other

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) of this project.

### PR DESCRIPTION
**Pull request by Asymtode712**
# 🎯 Title and Issue Number

### Closes #79

# 🗒️ Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X]  I have gone through `rules of when PR will get merged.` 
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have created a helpful and easy to understand `README.md`
- [X] I have followed proper file structure.
- [X] I have gone through [CONTRIBUTING GUIDELINES.md](../blob/master/CONTRIBUTING.md).

 Thank you for contributing!❤️ 

Don't forget to show some love by ⭐ the repository!

### CODE REVIEW

**Comment by dishamodi0910** [comment]
Hey @Asymtode712, Thank you for creating PR! We will review it super soon. 😇❣️
As we continue to evolve and innovate, we encourage you to share your ideas, feedback, and code to help us push the boundaries of what's possible in the world of APIs🚀.
We hope you have followed [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md).
Thank you for being an essential part of our community. Together, we'll keep building amazing things!
Don’t forget to ⭐ our repository!
Happy Coding!✨
Will See you soon❣️

**Review by dishamodi0910 — CHANGES_REQUESTED** [review]
Hey @Asymtode712, Instead of using the sample data from your side, try to use MONGODB database inorder to make one completely aware of how they can interact with database instead of static data for achieving the same functionality.

This would be more beneficial to let this PR go under LEVEL 3 for GSSOC'24!

**Comment by Asymtode712** [comment]
Sure! Working on your suggestion!!!

**Comment by Asymtode712** [comment]
Hey @dishamodi0910, I have connected MongoDB to avoid the use of static data. Please check my PR and merge it if it is good to go

**Comment by dishamodi0910** [comment]
Yup, looks great now @Asymtode712✨!

**Review by dishamodi0910 — APPROVED** [review]

**Comment by dishamodi0910** [comment]
@Asymtode712 We're thrilled to inform you that your pull request has been successfully merged into the APIverse🚀🎁
Your hard work, dedication, and expertise have made a significant impact on our project, and we couldn't be more grateful for your contributions.😇
Your code will now be a part of our growing ecosystem, helping developers worldwide to create exceptional APIs.❣️🔥
Happy Coding! ✨
Will See you soon❣️

**Comment by Asymtode712** [comment]
@dishamodi0910 please assign me this PR

**Pull request merged**
