### PR TITLE
Zomato API

### LINKED ISSUE #372: [New API] : Zomato API
### Brief Description 🤓

The Zomato API provides access to Zomato's extensive database of restaurants, including information on menus, reviews, locations, and ratings. Developers can use this API to integrate restaurant search, discovery, and food-related services into their applications, enabling features like finding nearby restaurants, reading reviews, or checking out menus.

### How will you develop it?🤩

React, JavaScript

### Deployment

None

### Select the open source program you are contributing to

Other

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) of this project.

### PR DESCRIPTION
**Pull request by revanth1718**
# 🎯 Title and Issue Number

[New API] : Zomato API #372

### Closes #372 <issue_no>

image

# 🗒️ Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x]  I have gone through `rules of when PR will get merged.` 
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have followed proper file structure.
- [x] I have gone through [CONTRIBUTING GUIDELINES.md](../blob/master/CONTRIBUTING.md).

@dinxsh, @dishamodi0910 view this PR

### CODE REVIEW

**Comment by dishamodi0910** [comment]
Hey @revanth1718, Thank you for creating PR! We will review it super soon. 😇❣️
As we continue to evolve and innovate, we encourage you to share your ideas, feedback, and code to help us push the boundaries of what's possible in the world of APIs🚀.
We hope you have followed [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md).
Thank you for being an essential part of our community. Together, we'll keep building amazing things!
Don’t forget to ⭐ our repository!
Happy Coding!✨
Will See you soon❣️

**Comment by revanth1718** [comment]
@dinxsh kindly merge this API

**Review by dinxsh — APPROVED** [review]
lgtm

**Comment by dishamodi0910** [comment]
@revanth1718 We're thrilled to inform you that your pull request has been successfully merged into the APIverse🚀🎁
Your hard work, dedication, and expertise have made a significant impact on our project, and we couldn't be more grateful for your contributions.😇
Your code will now be a part of our growing ecosystem, helping developers worldwide to create exceptional APIs.❣️🔥
Happy Coding! ✨
Will See you soon❣️

**Pull request merged**
