### PR TITLE
Added Anime Api

### LINKED ISSUE #274: [New API] :  Add Amine image generation API
### Brief Description 🤓

This anime image generation API provides users with a fun and creative way to generate custom anime-style images using web technologies.

Please assign it to me under gssoc

### How will you develop it?🤩

Develop an API using HTML, CSS, and JavaScript to dynamically generate anime-style images, incorporating randomness and user customization for character and background selection. Provide an intuitive web interface for users to interact with the API and generate images easily.

### Deployment

None

### Select the open source program you are contributing to

Other

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) of this project.

### PR DESCRIPTION
**Pull request by ananyag309**
# 🎯 Title and Issue Number
Added anime fact api

### Closes #274 

# 🗒️ Checklist:

- [y] I have mentioned the issue number in my Pull Request.
- [y]  I have gone through `rules of when PR will get merged.` 
- [y] I have commented my code, particularly in hard-to-understand areas
- [y] I have created a helpful and easy to understand `README.md`
- [y] I have followed proper file structure.
- [y] I have gone through [CONTRIBUTING GUIDELINES.md](../blob/master/CONTRIBUTING.md).

 Thank you for contributing!❤️ 

Don't forget to show some love by ⭐ the repository!

### CODE REVIEW

**Comment by dishamodi0910** [comment]
Hey @ananyag309, Thank you for creating PR! We will review it super soon. 😇❣️
As we continue to evolve and innovate, we encourage you to share your ideas, feedback, and code to help us push the boundaries of what's possible in the world of APIs🚀.
We hope you have followed [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md).
Thank you for being an essential part of our community. Together, we'll keep building amazing things!
Don’t forget to ⭐ our repository!
Happy Coding!✨
Will See you soon❣️

**Comment by dishamodi0910** [comment]
Hey @ananyag309, As you are already using the api from the project maintained by someone else, would want that you move this folder under the already existing api's folder. Also please remove the code portion mentioned in README.md

**Comment by ananyag309** [comment]
@dishamodi0910 sure i am making the necessary changes

**Comment by dishamodi0910** [comment]
@ananyag309 ,I wanted to reach out and let you know that we have decided to close your pull request.🙇

In case of any issues, you can contact us on [Discord](https://discord.gg/mv4NTzN).
Thank you! ❣️
Happy Coding! ✨
Will See you soon❣️

**Review by dinxsh — APPROVED** [review]
good job!

**Comment by ananyag309** [comment]
@dinxsh thank you 
please merge it as 10th is the last date @dishamodi0910

**Comment by dishamodi0910** [comment]
@ananyag309 We're thrilled to inform you that your pull request has been successfully merged into the APIverse🚀🎁
Your hard work, dedication, and expertise have made a significant impact on our project, and we couldn't be more grateful for your contributions.😇
Your code will now be a part of our growing ecosystem, helping developers worldwide to create exceptional APIs.❣️🔥
Happy Coding! ✨
Will See you soon❣️

**Comment by ananyag309** [comment]
@dinxsh @dishamodi0910 please add gssoc and level label too and my name under assignes otherwise the points won't be counted under gssoc please

**Comment by ananyag309** [comment]
@Kritika30032002  @dinxsh @dishamodi0910 please add gssoc and level label too and my name under assignes otherwise the points won't be counted under gssoc please

**Comment by ananyag309** [comment]
@Kritika30032002 ma'am please help me out!!!

**Comment by dishamodi0910** [comment]
I hope that works now @ananyag309

**Comment by ananyag309** [comment]
thank you ma'am

**Pull request merged**
