### PR TITLE
done and dusted with NewsBuster #65

### LINKED ISSUE #65: [New API] : NewsBuster
### Brief Description 🤓

Aggregate news articles from various sources and categorize them based on topics like sports, technology, politics, etc. Users can search for news articles and filter them by date or source.

### How will you develop it?🤩

Reactjs

### Deployment

None

### Select the open source program you are contributing to

Other

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) of this project.

### PR DESCRIPTION
**Pull request by shambhaveesrivastava12**
# 🎯 NewsBuster #65 

### Closes #65 

# 🗒️ Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x]  I have gone through `rules of when PR will get merged.` 
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have followed proper file structure.
- [x] I have gone through [CONTRIBUTING GUIDELINES.md](../blob/master/CONTRIBUTING.md).

 Thank you for contributing!❤️ 

Don't forget to show some love by ⭐ the repository!

### CODE REVIEW

**Comment by dishamodi0910** [comment]
Hey @shambhaveesrivastava12, Thank you for creating PR! We will review it super soon. 😇❣️
As we continue to evolve and innovate, we encourage you to share your ideas, feedback, and code to help us push the boundaries of what's possible in the world of APIs🚀.
We hope you have followed [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md).
Thank you for being an essential part of our community. Together, we'll keep building amazing things!
Don’t forget to ⭐ our repository!
Happy Coding!✨
Will See you soon❣️

**Review by dishamodi0910 — CHANGES_REQUESTED** [review]
Hello @shambhaveesrivastava12, Awesome work ✨,
Please make following changes so I can approve and merge your PR under GSSoC24. 

1. Change the folder directory from NEW API's to Existing API Collection folder.
2. Add information about the already existing API that you are using to generate the response in the README.md file inside your folder.
3. Don't forget to make your entry in the linked [README.md file](https://github.com/dishamodi0910/APIVerse/blob/master/Existing_API_Collection/README.md).
4. Squash all your commits into a single commit.

**Comment by shambhaveesrivastava12** [comment]
done with the requested change ✅ @dishamodi0910

**Comment by dishamodi0910** [comment]
Please squash this commits into single commit and reopen PR.

**Comment by dishamodi0910** [comment]
@shambhaveesrivastava12 ,I wanted to reach out and let you know that we have decided to close your pull request.🙇

In case of any issues, you can contact us on [Discord](https://discord.gg/mv4NTzN).
Thank you! ❣️
Happy Coding! ✨
Will See you soon❣️

**Pull request closed without merging**
