### PR TITLE
added Countries API

### LINKED ISSUE #305: [New API] :  Countries and Capitals API
### Brief Description 🤓

In this API, users can call the countries and data will be returned in the JSON format.
Users will get:
1. Country
2. Capital
3. Language Spoken Majorly
4. Latitude
5. Longitude
6. Currency

### How will you develop it?🤩

I will create this API in Node.js to serve country data in JSON format involves the following steps:
1. Set up the project and install dependencies
2. Create the server
3. Define routes
4. Create a data source
5. Handle requests and send responses

### Deployment

No

### Select the open source program you are contributing to

Other

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) of this project.

### PR DESCRIPTION
**Pull request by abckhush**
# 🎯 [New API] : Countries and Capitals API #305

### Closes #305

image
image
image
image

# 🗒️ Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X]  I have gone through `rules of when PR will get merged.` 
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have created a helpful and easy to understand `README.md`
- [X] I have followed proper file structure.
- [X] I have gone through [CONTRIBUTING GUIDELINES.md](../blob/master/CONTRIBUTING.md).

 Thank you for contributing!❤️ 

Don't forget to show some love by ⭐ the repository!

### CODE REVIEW

**Comment by dishamodi0910** [comment]
Hey @abckhush, Thank you for creating PR! We will review it super soon. 😇❣️
As we continue to evolve and innovate, we encourage you to share your ideas, feedback, and code to help us push the boundaries of what's possible in the world of APIs🚀.
We hope you have followed [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md).
Thank you for being an essential part of our community. Together, we'll keep building amazing things!
Don’t forget to ⭐ our repository!
Happy Coding!✨
Will See you soon❣️

**Comment by dishamodi0910** [comment]
Hey @abckhush, It is great one, it has currently a limitation, that you are providing the hardcoded data, just wanted that if you can keep this in form of endpoint, like a endpoint, from where I can add that data to database, and all the operations of fetching data should happen from db.
Looking forward to hearing from you!

**Comment by abckhush** [comment]
@dishamodi0910 like you want a database, in which we can add country data also? Or use the same db file as the endpoint for adding and fetching data?

**Comment by abckhush** [comment]
You can now add, delete, and update the database file now.
@dishamodi0910 Kindly review these changes.

Screenshot 2024-07-27 121138
Screenshot 2024-07-27 134417

**Comment by abckhush** [comment]
@dishamodi0910 Kindly merge this. Only a few days are left.

**Comment by abckhush** [comment]
@dishamodi0910 It's 30th today. Kindly merge this.

**Comment by dishamodi0910** [comment]
@abckhush We're thrilled to inform you that your pull request has been successfully merged into the APIverse🚀🎁
Your hard work, dedication, and expertise have made a significant impact on our project, and we couldn't be more grateful for your contributions.😇
Your code will now be a part of our growing ecosystem, helping developers worldwide to create exceptional APIs.❣️🔥
Happy Coding! ✨
Will See you soon❣️

**Pull request merged**
