### PR TITLE
Added New API - Library API

### LINKED ISSUE #56: [New API] : Library API
### Brief Description 🤓

The Library API will be responsible for all the task that a library performs to store the data effieciently.
**Adding Books**
**Lending Books**
**Getting Customers Registered**
**Collecting Books**
and much more

### How will you develop it?🤩

I would develop it using the powers of **Express JS** and my knowledge of APIs

### Deployment

None

### Select the open source program you are contributing to

Other

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) of this project.

### PR DESCRIPTION
**Pull request by mdrehan369**
# 🎯 Title and Issue Number

### Closes #56 

# 🗒️ Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x]  I have gone through `rules of when PR will get merged.` 
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have followed proper file structure.
- [x] I have gone through [CONTRIBUTING GUIDELINES.md](../blob/master/CONTRIBUTING.md).

 Thank you for contributing!❤️ 

Don't forget to show some love by ⭐ the repository!

### CODE REVIEW

**Comment by dishamodi0910** [comment]
Hey @mdrehan369, Thank you for creating PR! We will review it super soon. 😇❣️
As we continue to evolve and innovate, we encourage you to share your ideas, feedback, and code to help us push the boundaries of what's possible in the world of APIs🚀.
We hope you have followed [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md).
Thank you for being an essential part of our community. Together, we'll keep building amazing things!
Don’t forget to ⭐ our repository!
Happy Coding!✨
Will See you soon❣️

**Comment by dishamodi0910** [comment]
@mdrehan369, Great job! 🚀

It would be great if you could add the feature of penalty as well that is set the expiry time once someone borrows the book. Make sure that they return the book within the expiry time, or else they would be charged some penalty, This could be great addition to boost this PR to level 3!

**Review by dishamodi0910 — CHANGES_REQUESTED** [review]
Changes required as mentioned!

**Comment by mdrehan369** [comment]
> Changes required as mentioned!

Okay mam I am on it!

**Comment by mdrehan369** [comment]
I added the requested functionality #72

**Comment by dishamodi0910** [comment]
Looks good now @mdrehan369!🎇

**Review by dishamodi0910 — APPROVED** [review]

**Comment by dishamodi0910** [comment]
@mdrehan369 We're thrilled to inform you that your pull request has been successfully merged into the APIverse🚀🎁
Your hard work, dedication, and expertise have made a significant impact on our project, and we couldn't be more grateful for your contributions.😇
Your code will now be a part of our growing ecosystem, helping developers worldwide to create exceptional APIs.❣️🔥
Happy Coding! ✨
Will See you soon❣️

**Pull request merged**
