### PR TITLE
[New API] : Auto Detect Tags from Text API

### LINKED ISSUE #280: [New API] : Auto Detect Tags from Text API
### Brief Description 🤓

To detect tags from the text and return an array of them. The tags are nothing but the keywords that are describing the text.

### How will you develop it?🤩

I will develop the API in javascript in the NodeJS environment. It will contain a post request.

### Deployment

None

### Select the open source program you are contributing to

Other

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) of this project.

### PR DESCRIPTION
**Pull request by SatwikMohan**
# 🎯 Title and Issue Number

Title - [New API] : Auto Detect Tags from Text API
Issue Number - #280 

### Closes #280 

# 🗒️ Checklist:

- [Y] I have mentioned the issue number in my Pull Request.
- [Y]  I have gone through `rules of when PR will get merged.` 
- [Y] I have commented my code, particularly in hard-to-understand areas
- [Y] I have created a helpful and easy to understand `README.md`
- [Y] I have followed proper file structure.
- [Y] I have gone through [CONTRIBUTING GUIDELINES.md](../blob/master/CONTRIBUTING.md).

 Thank you for contributing!❤️ 

Don't forget to show some love by ⭐ the repository!

### CODE REVIEW

**Comment by dishamodi0910** [comment]
Hey @SatwikMohan, Thank you for creating PR! We will review it super soon. 😇❣️
As we continue to evolve and innovate, we encourage you to share your ideas, feedback, and code to help us push the boundaries of what's possible in the world of APIs🚀.
We hope you have followed [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md).
Thank you for being an essential part of our community. Together, we'll keep building amazing things!
Don’t forget to ⭐ our repository!
Happy Coding!✨
Will See you soon❣️

**Comment by dishamodi0910** [comment]
@SatwikMohan This PR contains commits of 5-6 APIs. Please make a separate commit for separate API. One commit should not have more than 1 API folders.

**Comment by dishamodi0910** [comment]
@SatwikMohan Closing this PR, create a new PR with 1 API in 1 PR.

**Comment by dishamodi0910** [comment]
@SatwikMohan ,I wanted to reach out and let you know that we have decided to close your pull request.🙇

In case of any issues, you can contact us on [Discord](https://discord.gg/mv4NTzN).
Thank you! ❣️
Happy Coding! ✨
Will See you soon❣️

**Comment by SatwikMohan** [comment]
@dishamodi0910  Mam I think you should review it from the first commit i.e. from #233 then all the commits will automatically decrease because I have committed every time by creating a new branch in my fork branch.

**Pull request closed without merging**
