### PR TITLE
Adding a new Payment API

### LINKED ISSUE #277: [New API] : Payment API
### Brief Description 🤓

Payment gateways are essential for handling online transactions, providing secure methods for processing payments via credit cards, bank transfers, and other methods.

### How will you develop it?🤩

- I am going to use PayPal API for Payment API
- For frontend HTML, CSS, Javascript 
- for backend Node.js

### Deployment

None

### Select the open source program you are contributing to

Other

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) of this project.

### PR DESCRIPTION
**Pull request by Bhumika1312**
# 🎯 Title and Issue Number

Payment API demonstrates how to integrate PayPal API for online payments
### Closes #277 

# 🗒️ Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x]  I have gone through `rules of when PR will get merged.` 
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have followed proper file structure.
- [x] I have gone through [CONTRIBUTING GUIDELINES.md](../blob/master/CONTRIBUTING.md).

 Thank you for contributing!❤️ 

Don't forget to show some love by ⭐ the repository!

### CODE REVIEW

**Comment by dishamodi0910** [comment]
Hey @Bhumika1312, Thank you for creating PR! We will review it super soon. 😇❣️
As we continue to evolve and innovate, we encourage you to share your ideas, feedback, and code to help us push the boundaries of what's possible in the world of APIs🚀.
We hope you have followed [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md).
Thank you for being an essential part of our community. Together, we'll keep building amazing things!
Don’t forget to ⭐ our repository!
Happy Coding!✨
Will See you soon❣️

**Comment by Bhumika1312** [comment]
@dishamodi0910  Can you please review this PR

**Comment by Bhumika1312** [comment]
@dishamodi0910 Can you review this PR
Thank you

**Comment by dishamodi0910** [comment]
@Bhumika1312 Please remove client_id and client_secret, configure them in .env file and use from there, do not expose your credentials.
Please remove them and make changes.

**Comment by Bhumika1312** [comment]
@dishamodi0910 made the changes as requested. Please review it
Thank you

**Comment by Kritika30032002** [comment]
@dishamodi0910

**Comment by Bhumika1312** [comment]
@dishamodi0910 Please review this PR I have made the required changes

**Comment by Bhumika1312** [comment]
@dishamodi0910 Can you please review this

**Comment by dishamodi0910** [comment]
@Bhumika1312 We're thrilled to inform you that your pull request has been successfully merged into the APIverse🚀🎁
Your hard work, dedication, and expertise have made a significant impact on our project, and we couldn't be more grateful for your contributions.😇
Your code will now be a part of our growing ecosystem, helping developers worldwide to create exceptional APIs.❣️🔥
Happy Coding! ✨
Will See you soon❣️

**Pull request merged**
