### PR TITLE
the freeMeal api is added

### LINKED ISSUE #235: [Existing API Name] : FreeMealsdb api to get Food data
### Brief Description 🤓

The FreeMealDB API is like a big library of recipes and food info that anyone can use. It helps people find out about different kinds of food, how to cook them, and what's in them. It's easy to use and great for anyone who loves food or wants to make cooking apps or websites.

### Provide reference!

https://www.themealdb.com/api.php/

### Select the open source program you are contributing to

Other

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) of this project.

### PR DESCRIPTION
**Pull request by Sypher0Dronzer**
# 🎯 FreeMealDB Issue Number: #235

### Closes #235

# 🗒️ Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x]  I have gone through `rules of when PR will get merged.` 
- [x] I have commented my code, particularly in hard-to-understand areas
- [] I have created a helpful and easy to understand `README.md`
- [x] I have followed proper file structure.
- [x] I have gone through [CONTRIBUTING GUIDELINES.md](../blob/master/CONTRIBUTING.md).

 Thank you for contributing!❤️ 

Don't forget to show some love by ⭐ the repository!

### CODE REVIEW

**Comment by dishamodi0910** [comment]
Hey @Sypher0Dronzer, Thank you for creating PR! We will review it super soon. 😇❣️
As we continue to evolve and innovate, we encourage you to share your ideas, feedback, and code to help us push the boundaries of what's possible in the world of APIs🚀.
We hope you have followed [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md).
Thank you for being an essential part of our community. Together, we'll keep building amazing things!
Don’t forget to ⭐ our repository!
Happy Coding!✨
Will See you soon❣️

**Comment by dishamodi0910** [comment]
@Sypher0Dronzer Please add README.md to your folder mentioning about API

**Review by dinxsh — APPROVED** [review]
good job!

**Comment by dishamodi0910** [comment]
@Sypher0Dronzer We're thrilled to inform you that your pull request has been successfully merged into the APIverse🚀🎁
Your hard work, dedication, and expertise have made a significant impact on our project, and we couldn't be more grateful for your contributions.😇
Your code will now be a part of our growing ecosystem, helping developers worldwide to create exceptional APIs.❣️🔥
Happy Coding! ✨
Will See you soon❣️

**Pull request merged**
