### PR TITLE
Blog Platform api

### LINKED ISSUE #342: [New API] : Blog platform api
### Brief Description 🤓

backend infrastructure for "Bloggie," a versatile blogging platform, using Node.js, Express.js, and MongoDB, facilitating seamless management of user and admin roles with role-based authentication.

robust user authentication functionalities, including sign-in and sign-up features, ensuring secure access for both users and administrators.

intuitive blogs management features, enabling users to create, edit, and delete blog posts, fostering dynamic content creation.

likes and comments management capabilities, enhancing user engagement and interaction within the platform.

tag-based search functionality, allowing users to easily discover relevant blogs by tags, optimizing content discovery and user experience.

tag management functionalities for administrators, enabling CRUD operations for tags, ensuring flexible and dynamic content categorization.

### How will you develop it?🤩

Using node.js, express.js and mongodb

### Deployment

None

### Select the open source program you are contributing to

Other

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) of this project.

### PR DESCRIPTION
**Pull request by DharshiBalasubramaniyam**
# 🎯 Title and Issue Number

issue #342 - Blog platform

Closes #342

add_comment
create_blog
get_all_blogs
get_all_tags
like_unlike
login_user
register_user

# 🗒️ Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x]  I have gone through `rules of when PR will get merged.` 
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have followed proper file structure.
- [x] I have gone through [CONTRIBUTING GUIDELINES.md](../blob/master/CONTRIBUTING.md).

 Thank you for contributing!❤️ 

Don't forget to show some love by ⭐ the repository!

### CODE REVIEW

**Comment by dishamodi0910** [comment]
Hey @DharshiBalasubramaniyam, Thank you for creating PR! We will review it super soon. 😇❣️
As we continue to evolve and innovate, we encourage you to share your ideas, feedback, and code to help us push the boundaries of what's possible in the world of APIs🚀.
We hope you have followed [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md).
Thank you for being an essential part of our community. Together, we'll keep building amazing things!
Don’t forget to ⭐ our repository!
Happy Coding!✨
Will See you soon❣️

**Comment by DharshiBalasubramaniyam** [comment]
@dishamodi0910 Kindly review this pr

**Comment by DharshiBalasubramaniyam** [comment]
@dishamodi0910. Please kindly review the pr

**Review by Kritika30032002 — APPROVED** [review]

**Comment by dishamodi0910** [comment]
@DharshiBalasubramaniyam We're thrilled to inform you that your pull request has been successfully merged into the APIverse🚀🎁
Your hard work, dedication, and expertise have made a significant impact on our project, and we couldn't be more grateful for your contributions.😇
Your code will now be a part of our growing ecosystem, helping developers worldwide to create exceptional APIs.❣️🔥
Happy Coding! ✨
Will See you soon❣️

**Pull request merged**
