### PR TITLE
IIT ISM Subjects API Issue [#69]

### PR DESCRIPTION
**Pull request by pspriyanshu601**
# 🎯 [New API] : IIT ISM Subjects API issue 69

### Closes [#<69](https://github.com/dishamodi0910/APIVerse/issues/69)

# 🗒️ Checklist:
- [x] I have mentioned the issue number in my Pull Request.
- [x] I have gone through `rules of when PR will get merged.` 
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have followed proper file structure.
- [x] I have gone through [CONTRIBUTING GUIDELINES.md](../blob/master/CONTRIBUTING.md).
 Thank you for contributing!❤️ 

Don't forget to show some love by ⭐ the repository!

### CODE REVIEW

**Comment by dishamodi0910** [comment]
Hey @pspriyanshu601, Thank you for creating PR! We will review it super soon. 😇❣️
As we continue to evolve and innovate, we encourage you to share your ideas, feedback, and code to help us push the boundaries of what's possible in the world of APIs🚀.
We hope you have followed [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md).
Thank you for being an essential part of our community. Together, we'll keep building amazing things!
Don’t forget to ⭐ our repository!
Happy Coding!✨
Will See you soon❣️

**Comment by pspriyanshu601** [comment]
@dishamodi0910 Please review my PR , I dont have any merge conflicts .

**Review by dishamodi0910 — CHANGES_REQUESTED** [review]
Please remove the example responses from README.md file. 
Mention about where this API can be used in README.md file.

**Comment by pspriyanshu601** [comment]
@dishamodi0910  I have removed the example responses and mentioned about where this api can be used in the README.md file as you asked for .
Please review this and merge , a quick response will be appreciated .

**Review by dishamodi0910 — APPROVED** [review]

**Comment by dishamodi0910** [comment]
Looks good @pspriyanshu601😄!

**Comment by dishamodi0910** [comment]
@pspriyanshu601 We're thrilled to inform you that your pull request has been successfully merged into the APIverse🚀🎁
Your hard work, dedication, and expertise have made a significant impact on our project, and we couldn't be more grateful for your contributions.😇
Your code will now be a part of our growing ecosystem, helping developers worldwide to create exceptional APIs.❣️🔥
Happy Coding! ✨
Will See you soon❣️

**Pull request merged**
