### PR TITLE
[New API] : Auth API

### LINKED ISSUE #57: [New API] :  Authentication API
### Brief Description 🤓

An authentication API is a service that manages user authentication for applications. It provides endpoints for user registration, login, and password management.

- User Registration: Users can create new accounts by providing a username, email address, and password. The API securely stores user credentials and generates a unique identifier for each user.
- User Login: Users can authenticate themselves and log in to their accounts using their username/email and password. Upon successful authentication, the API issues a token that the user can use to access protected resources.
- Token Management: Tokens are used for authentication and session management. Upon successful login, the API issues a JSON Web Token (JWT) containing user information and expiration time. The token is sent with each subsequent request for authentication.
- Password Management: Users can reset their passwords if they forget them or change their passwords if needed. The API securely hashes and stores passwords to protect user data.

### How will you develop it?🤩

To develop an API, I'd start by designing the endpoints and data structures needed to fulfill the requirements of the application. Then, I'd choose a technology stack that aligns with the project's goals and requirements, such as Node.js and Express.js for building a RESTful API. Next, I'd implement the API endpoints, handling requests and responses, as well as any authentication or authorization mechanisms needed. Finally, I'd thoroughly test the API to ensure it behaves as expected and meets the project's specifications. Throughout the development process, I'd focus on simplicity, scalability, and security, following best practices for API design and development.

### Deployment

No

### Select the open source program you are contributing to

Other

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) of this project.

### PR DESCRIPTION
**Pull request by sum1t-here**
# 🎯 [New API] : Auth API #57

### Closes #57

# 🗒️ Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x]  I have gone through `rules of when PR will get merged.` 
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have followed proper file structure.
- [x] I have gone through [CONTRIBUTING GUIDELINES.md](../blob/master/CONTRIBUTING.md).

 Thank you for contributing!❤️ 

Don't forget to show some love by ⭐ the repository!

### CODE REVIEW

**Comment by dishamodi0910** [comment]
Hey @sum1t-here, Thank you for creating PR! We will review it super soon. 😇❣️
As we continue to evolve and innovate, we encourage you to share your ideas, feedback, and code to help us push the boundaries of what's possible in the world of APIs🚀.
We hope you have followed [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md).
Thank you for being an essential part of our community. Together, we'll keep building amazing things!
Don’t forget to ⭐ our repository!
Happy Coding!✨
Will See you soon❣️

**Comment by sum1t-here** [comment]
Hi @dishamodi0910 please check the pull request and merge it on the behalf of GSSOC'24

**Comment by dishamodi0910** [comment]
@sum1t-here ,I wanted to reach out and let you know that we have decided to close your pull request.🙇

In case of any issues, you can contact us on [Discord](https://discord.gg/mv4NTzN).
Thank you! ❣️
Happy Coding! ✨
Will See you soon❣️

**Comment by sum1t-here** [comment]
# 🎯 [New API] : Auth API #58



### Closes #58



# 🗒️ Checklist:

- [.] I have mentioned the issue number in my Pull Request.
- [.]  I have gone through `rules of when PR will get merged.` 
- [.] I have commented my code, particularly in hard-to-understand areas
- [.] I have created a helpful and easy to understand `README.md`
- [.] I have followed proper file structure.
- [.] I have gone through [CONTRIBUTING GUIDELINES.md](../blob/master/CONTRIBUTING.md).

 Thank you for contributing!❤️ 

Don't forget to show some love by ⭐ the repository!

**Review by dishamodi0910 — APPROVED** [review]

**Comment by dishamodi0910** [comment]
@sum1t-here We're thrilled to inform you that your pull request has been successfully merged into the APIverse🚀🎁
Your hard work, dedication, and expertise have made a significant impact on our project, and we couldn't be more grateful for your contributions.😇
Your code will now be a part of our growing ecosystem, helping developers worldwide to create exceptional APIs.❣️🔥
Happy Coding! ✨
Will See you soon❣️

**Pull request merged**
