### PR TITLE
created a new random user generator api

### LINKED ISSUE #90: [New API] : Random User API
### Brief Description 🤓

The Random User API is a simple yet powerful tool for generating random user data for testing and development purposes. It allows developers to retrieve random user information such as names, email addresses, phone numbers, and profile pictures in various formats, including JSON, CSV, and YAML.

### How will you develop it?🤩

Will be using @faker-js/faker npm package for devloping the random user api

### Deployment

No

### Select the open source program you are contributing to

Other

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) of this project.

### PR DESCRIPTION
**Pull request by sum1t-here**
# 🎯 Title and Issue Number

### Closes #90 

# 🗒️ Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x]  I have gone through `rules of when PR will get merged.` 
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have followed proper file structure.
- [x] I have gone through [CONTRIBUTING GUIDELINES.md](../blob/master/CONTRIBUTING.md).

 Thank you for contributing!❤️ 

Don't forget to show some love by ⭐ the repository!

### CODE REVIEW

**Comment by dishamodi0910** [comment]
Hey @sum1t-here, Thank you for creating PR! We will review it super soon. 😇❣️
As we continue to evolve and innovate, we encourage you to share your ideas, feedback, and code to help us push the boundaries of what's possible in the world of APIs🚀.
We hope you have followed [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md).
Thank you for being an essential part of our community. Together, we'll keep building amazing things!
Don’t forget to ⭐ our repository!
Happy Coding!✨
Will See you soon❣️

**Comment by dishamodi0910** [comment]
@sum1t-here, In README.md, mention the use case where this API can be used. No need to have the response you get in the README.md file. Also, make sure to add more functionality so that the PR can come under LEVEL 3.

**Comment by sum1t-here** [comment]
hey can you check the changes @dishamodi0910

**Review by dishamodi0910 — APPROVED** [review]

**Comment by dishamodi0910** [comment]
@sum1t-here We're thrilled to inform you that your pull request has been successfully merged into the APIverse🚀🎁
Your hard work, dedication, and expertise have made a significant impact on our project, and we couldn't be more grateful for your contributions.😇
Your code will now be a part of our growing ecosystem, helping developers worldwide to create exceptional APIs.❣️🔥
Happy Coding! ✨
Will See you soon❣️

**Pull request merged**
