### PR TITLE
Changed unsplash folder into the existingAPI Folder

### PR DESCRIPTION
**Pull request by haard18**
🎯 Title and Issue Number
Unsplash API Implemented https://github.com/dishamodi0910/APIVerse/issues/71

Closes https://github.com/dishamodi0910/APIVerse/issues/71
🗒️ Checklist:
 I have mentioned the issue number in my Pull Request.
 I have gone through rules of when PR will get merged.
 I have commented my code, particularly in hard-to-understand areas
 I have created a helpful and easy to understand README.md
 I have followed proper file structure.
 I have gone through [CONTRIBUTING GUIDELINES.md](https://github.com/dishamodi0910/APIVerse/blob/master/CONTRIBUTING.md).
Thank you for contributing!❤️

Don't forget to show some love by ⭐ the repository!

### CODE REVIEW

**Comment by dishamodi0910** [comment]
Hey @haard18, Thank you for creating PR! We will review it super soon. 😇❣️
As we continue to evolve and innovate, we encourage you to share your ideas, feedback, and code to help us push the boundaries of what's possible in the world of APIs🚀.
We hope you have followed [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md).
Thank you for being an essential part of our community. Together, we'll keep building amazing things!
Don’t forget to ⭐ our repository!
Happy Coding!✨
Will See you soon❣️

**Comment by dishamodi0910** [comment]
@haard18, Make entry of API into [README.md file](https://github.com/dishamodi0910/APIVerse/blob/master/Existing_API_Collection/README.md)

**Comment by haard18** [comment]
Check Now @dishamodi0910

**Review by dishamodi0910 — APPROVED** [review]

**Comment by dishamodi0910** [comment]
@haard18 We're thrilled to inform you that your pull request has been successfully merged into the APIverse🚀🎁
Your hard work, dedication, and expertise have made a significant impact on our project, and we couldn't be more grateful for your contributions.😇
Your code will now be a part of our growing ecosystem, helping developers worldwide to create exceptional APIs.❣️🔥
Happy Coding! ✨
Will See you soon❣️

**Pull request merged**
