### PR TITLE
email checker added

### LINKED ISSUE #190: [New API] : API that checks email is genuine or not
### Brief Description 🤓

This API will help to filter out genuine email ID.

### How will you develop it?🤩

I will add an API that will Checks the email is genuine(permanent) or temporary(disposable).

Please assign me this work under GSSoC'24.

### Deployment

None

### Select the open source program you are contributing to

Other

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) of this project.

### PR DESCRIPTION
**Pull request by pankaj-bind**
# 🎯 Title and Issue Number

Issue number #190 API that checks email is genuine or not added

## Output

https://github.com/dishamodi0910/APIVerse/assets/73558583/cd8c5353-7f8a-47f7-983f-6dd8559daa83

# 🗒️ Checklist:

- [] I have mentioned the issue number in my Pull Request.
- []  I have gone through `rules of when PR will get merged.` 
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have created a helpful and easy to understand `README.md`
- [] I have followed proper file structure.
- [] I have gone through [CONTRIBUTING GUIDELINES.md](../blob/master/CONTRIBUTING.md).

 Thank you for contributing!❤️ 

Don't forget to show some love by ⭐ the repository!

### CODE REVIEW

**Comment by dishamodi0910** [comment]
Hey @pankaj-bind, Thank you for creating PR! We will review it super soon. 😇❣️
As we continue to evolve and innovate, we encourage you to share your ideas, feedback, and code to help us push the boundaries of what's possible in the world of APIs🚀.
We hope you have followed [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md).
Thank you for being an essential part of our community. Together, we'll keep building amazing things!
Don’t forget to ⭐ our repository!
Happy Coding!✨
Will See you soon❣️

**Comment by pankaj-bind** [comment]
Wait I forget readme.md

**Comment by Yashgabani845** [comment]
but sir it is existing API not new API
new API means you have to add all endpoints from you side 
https://disposable.debounce.io : this is real API
i am just clarifying you so that no conflict occure in future

**Comment by pankaj-bind** [comment]
ok, I'll make change

**Comment by pankaj-bind** [comment]
All changes made

**Comment by dishamodi0910** [comment]
@pankaj-bind We're thrilled to inform you that your pull request has been successfully merged into the APIverse🚀🎁
Your hard work, dedication, and expertise have made a significant impact on our project, and we couldn't be more grateful for your contributions.😇
Your code will now be a part of our growing ecosystem, helping developers worldwide to create exceptional APIs.❣️🔥
Happy Coding! ✨
Will See you soon❣️

**Pull request merged**
