### PR TITLE
OpenWeatherMap API Added

### LINKED ISSUE #226: [Existing API Name] : Open WeatherMap API
### Brief Description 🤓

The OpenWeatherMap API is a service that provides weather data, forecasts, and other related information. It can be integrate into applications to access current weather conditions, forecasts, historical weather data, and more. The API offers various endpoints for different types of weather data and supports multiple programming languages for easy integration.

### Provide reference!

https://openweathermap.org/api

### Select the open source program you are contributing to

Other

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) of this project.

### PR DESCRIPTION
**Pull request by anusha7530**
# 🎯 Title and Issue Number

[Existing API Name] : Open Weather Map API #226 

### Closes #226

Weather

# 🗒️ Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x]  I have gone through `rules of when PR will get merged.` 
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have followed proper file structure.
- [x] I have gone through [CONTRIBUTING GUIDELINES.md](../blob/master/CONTRIBUTING.md).

 Thank you for contributing!❤️ 

Don't forget to show some love by ⭐ the repository!

### CODE REVIEW

**Comment by dishamodi0910** [comment]
Hey @anusha7530, Thank you for creating PR! We will review it super soon. 😇❣️
As we continue to evolve and innovate, we encourage you to share your ideas, feedback, and code to help us push the boundaries of what's possible in the world of APIs🚀.
We hope you have followed [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md).
Thank you for being an essential part of our community. Together, we'll keep building amazing things!
Don’t forget to ⭐ our repository!
Happy Coding!✨
Will See you soon❣️

**Review by Kritika30032002 — APPROVED** [review]

**Comment by Kritika30032002** [comment]
@dishamodi0910

**Comment by anusha7530** [comment]
@dishamodi0910 Hey, kindly review my pull request, and merge it by assigning it to me and labelling it.

**Comment by anusha7530** [comment]
> Hey @anusha7530, Thank you for creating PR! We will review it super soon. 😇❣️ As we continue to evolve and innovate, we encourage you to share your ideas, feedback, and code to help us push the boundaries of what's possible in the world of APIs🚀. We hope you have followed [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md). Thank you for being an essential part of our community. Together, we'll keep building amazing things! Don’t forget to ⭐ our repository! Happy Coding!✨ Will See you soon❣️

@dishamodi0910 Hey, kindly review my pull request, and merge it by assigning it to me and labelling it.

**Comment by dishamodi0910** [comment]
Hey @anusha7530, we are already having one such API existing into the repo, you can contribute towards its enhancement, would like to close this one to avoid duplicate APIs.

**Comment by dishamodi0910** [comment]
@anusha7530 ,I wanted to reach out and let you know that we have decided to close your pull request.🙇

In case of any issues, you can contact us on [Discord](https://discord.gg/mv4NTzN).
Thank you! ❣️
Happy Coding! ✨
Will See you soon❣️

**Pull request closed without merging**
