### PR TITLE
Added Flora Monitoring System Using GenAI API

### LINKED ISSUE #108: [New API] :  Flora Monitoring System using GenAI
### Brief Description 🤓

Flora monitoring System with in-app chat and health checkups using Google's Gemini Pro models for vision and text analysis.

### How will you develop it?🤩

I build it using Node.js , Express.js ,  Multer For handling file Upload , Cloudinary , Gemini 

### Deployment

Yes

### Select the open source program you are contributing to

Other

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) of this project.

### PR DESCRIPTION
**Pull request by dfordp**
# 🎯 Title and Issue Number

### Closes #108 

# 🗒️ Checklist:

- [X] I have mentioned the issue number in my Pull Request.
- [X]  I have gone through `rules of when PR will get merged.` 
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have created a helpful and easy to understand `README.md`
- [X] I have followed proper file structure.
- [X] I have gone through [CONTRIBUTING GUIDELINES.md](../blob/master/CONTRIBUTING.md).

 Thank you for contributing!❤️ 

Don't forget to show some love by ⭐ the repository!

### CODE REVIEW

**Comment by dishamodi0910** [comment]
Hey @dfordp, Thank you for creating PR! We will review it super soon. 😇❣️
As we continue to evolve and innovate, we encourage you to share your ideas, feedback, and code to help us push the boundaries of what's possible in the world of APIs🚀.
We hope you have followed [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md).
Thank you for being an essential part of our community. Together, we'll keep building amazing things!
Don’t forget to ⭐ our repository!
Happy Coding!✨
Will See you soon❣️

**Review by dishamodi0910 — CHANGES_REQUESTED** [review]
@dfordp, Please mention about the endpoints in the README.md file properly. Also, try to mention about where this API can be used.

**Comment by dfordp** [comment]
Hi can you check now for the same

**Review by dishamodi0910 — APPROVED** [review]

**Comment by dishamodi0910** [comment]
@dfordp We're thrilled to inform you that your pull request has been successfully merged into the APIverse🚀🎁
Your hard work, dedication, and expertise have made a significant impact on our project, and we couldn't be more grateful for your contributions.😇
Your code will now be a part of our growing ecosystem, helping developers worldwide to create exceptional APIs.❣️🔥
Happy Coding! ✨
Will See you soon❣️

**Pull request merged**
