### PR TITLE
Movie Database API added

### LINKED ISSUE #127: [Existing API Name] : Movie Database
### Brief Description 🤓

 it is a api which is giving all details about movies which are recently relesed or according to filter we will provide , also it is giving detail about TV shows

### Provide reference!

TVmaze api

### Select the open source program you are contributing to

Other

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) of this project.

### PR DESCRIPTION
**Pull request by Yashgabani845**
# 🎯 Title and Issue Number

it is existing api for moveis and tv shows , this PR is adding 3 files , html,css and js for this api 
js file is fetching all movies and shows and then on searching it shows cards on html side

### Picture of Data and  Shows

Screenshot (73)

### Closes #127 

# 🗒️ Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x]  I have gone through `rules of when PR will get merged.` 
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have followed proper file structure.
- [x] I have gone through [CONTRIBUTING GUIDELINES.md](../blob/master/CONTRIBUTING.md).

 Thank you for contributing!❤️ 

Don't forget to show some love by ⭐ the repository!

### CODE REVIEW

**Comment by dishamodi0910** [comment]
Hey @Yashgabani845, Thank you for creating PR! We will review it super soon. 😇❣️
As we continue to evolve and innovate, we encourage you to share your ideas, feedback, and code to help us push the boundaries of what's possible in the world of APIs🚀.
We hope you have followed [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md).
Thank you for being an essential part of our community. Together, we'll keep building amazing things!
Don’t forget to ⭐ our repository!
Happy Coding!✨
Will See you soon❣️

**Comment by Yashgabani845** [comment]
in this PR in last commit i have removes all unrelated chnages to this issue you can check the files also only those files will be added in this PR which are related to this issue
Please go thorught files once 
I hope now there is no conflict from both PRs

**Review by dishamodi0910 — APPROVED** [review]

**Comment by dishamodi0910** [comment]
@Yashgabani845 We're thrilled to inform you that your pull request has been successfully merged into the APIverse🚀🎁
Your hard work, dedication, and expertise have made a significant impact on our project, and we couldn't be more grateful for your contributions.😇
Your code will now be a part of our growing ecosystem, helping developers worldwide to create exceptional APIs.❣️🔥
Happy Coding! ✨
Will See you soon❣️

**Pull request merged**
