### PR TITLE
Added Crypto Info API

### LINKED ISSUE #91: [New API] : Crypto Info API
### Brief Description 🤓

The API serves informational content for a wide variety of decentralized blockchains/cryptocurrencies and smart contract platforms.

### How will you develop it?🤩

Using the following tech stack - 
EJS
CSS
JavaScript
Node.js
Express

### Deployment

Yes

### Select the open source program you are contributing to

Other

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) of this project.

### PR DESCRIPTION
**Pull request by rahulkarda**
# 🎯 Title and Issue Number
Crypto Info API 

### Closes #91 

# 🗒️ Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x]  I have gone through `rules of when PR will get merged.` 
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have followed proper file structure.
- [x] I have gone through [CONTRIBUTING GUIDELINES.md](../blob/master/CONTRIBUTING.md).

 Thank you for contributing!❤️ 

Don't forget to show some love by ⭐ the repository!

### CODE REVIEW

**Comment by dishamodi0910** [comment]
Hey @rahulkarda, Thank you for creating PR! We will review it super soon. 😇❣️
As we continue to evolve and innovate, we encourage you to share your ideas, feedback, and code to help us push the boundaries of what's possible in the world of APIs🚀.
We hope you have followed [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md).
Thank you for being an essential part of our community. Together, we'll keep building amazing things!
Don’t forget to ⭐ our repository!
Happy Coding!✨
Will See you soon❣️

**Comment by dishamodi0910** [comment]
Hey @rahulkarda, PR is not proper. As it has submodule so I cannot merge it and it indicates that it is coming from some other repo. 
So closing this PR.

**Comment by dishamodi0910** [comment]
@rahulkarda ,I wanted to reach out and let you know that we have decided to close your pull request.🙇

In case of any issues, you can contact us on [Discord](https://discord.gg/mv4NTzN).
Thank you! ❣️
Happy Coding! ✨
Will See you soon❣️

**Comment by rahulkarda** [comment]
> Hey @rahulkarda, PR is not proper. As it has submodule so I cannot merge it and it indicates that it is coming from some other repo. So closing this PR.

what do you mean by submodules coming from another repo? It's my own repo only.

**Pull request closed without merging**
