### PR TITLE
translator api added

### LINKED ISSUE #178: [Existing API Name] : Google Translator API
### Brief Description 🤓

it is official API which is provided by google from translating text from ont language to other
it is certain limits but it is enough for us 
i want to fetch that api and put implementation here

### Provide reference!

https://translate.googleapis.com

### Select the open source program you are contributing to

Other

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) of this project.

### PR DESCRIPTION
**Pull request by Yashgabani845**
# 🎯 Title and Issue Number

[Existing API Name] : Google Translator API #178

### Closes #178 
Screenshot (188)

# 🗒️ Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x]  I have gone through `rules of when PR will get merged.` 
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have followed proper file structure.
- [x] I have gone through [CONTRIBUTING GUIDELINES.md](../blob/master/CONTRIBUTING.md).

 Thank you for contributing!❤️ 

Don't forget to show some love by ⭐ the repository!

### CODE REVIEW

**Comment by dishamodi0910** [comment]
Hey @Yashgabani845, Thank you for creating PR! We will review it super soon. 😇❣️
As we continue to evolve and innovate, we encourage you to share your ideas, feedback, and code to help us push the boundaries of what's possible in the world of APIs🚀.
We hope you have followed [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md).
Thank you for being an essential part of our community. Together, we'll keep building amazing things!
Don’t forget to ⭐ our repository!
Happy Coding!✨
Will See you soon❣️

**Comment by Yashgabani845** [comment]
@dishamodi0910  please review it 
if everything is well,
and make sure you assign me this PR and add labels so that no conflict occure in future
thank you

**Comment by dishamodi0910** [comment]
@Yashgabani845 The PR looks good to me, make sure that from next time whenever you use any external API and create PR, make sure that your clientId or API Key is not present as it would be publicly visible to all, so would suggest you to obfuscate it and mention that in steps in README.md of how they need to create the required API keys.

**Review by dishamodi0910 — APPROVED** [review]

**Comment by dishamodi0910** [comment]
@Yashgabani845 We're thrilled to inform you that your pull request has been successfully merged into the APIverse🚀🎁
Your hard work, dedication, and expertise have made a significant impact on our project, and we couldn't be more grateful for your contributions.😇
Your code will now be a part of our growing ecosystem, helping developers worldwide to create exceptional APIs.❣️🔥
Happy Coding! ✨
Will See you soon❣️

**Pull request merged**
