### PR TITLE
currency converter api implementation added

### LINKED ISSUE #146: [Existing API Name] :  Currency Exchange
### Brief Description 🤓

Live Currency Exchange Converter by specifying source and destination quote.
it  eill take input number and source that shows which currency you convert
and will tak destination that ill tell in which currency you want to convert
i will provide html file which option dropdown and will show exchanged amount

### Provide reference!

exchange generate API

### Select the open source program you are contributing to

Other

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) of this project.

### PR DESCRIPTION
**Pull request by Yashgabani845**
# 🎯 Title and Issue Number

it is implementation of existing API called freecurrrency api
i have added implemeenation of api  by html,js file and also gave style by css file

### Closes #146 

# 🗒️ Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x]  I have gone through `rules of when PR will get merged.` 
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have followed proper file structure.
- [x] I have gone through [CONTRIBUTING GUIDELINES.md](../blob/master/CONTRIBUTING.md).

# Here are few screenshots of my implementation

Screenshot (115)
Screenshot (116)

 Thank you for contributing!❤️ 

Don't forget to show some love by ⭐ the repository!

### CODE REVIEW

**Comment by dishamodi0910** [comment]
Hey @Yashgabani845, Thank you for creating PR! We will review it super soon. 😇❣️
As we continue to evolve and innovate, we encourage you to share your ideas, feedback, and code to help us push the boundaries of what's possible in the world of APIs🚀.
We hope you have followed [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md).
Thank you for being an essential part of our community. Together, we'll keep building amazing things!
Don’t forget to ⭐ our repository!
Happy Coding!✨
Will See you soon❣️

**Review by dishamodi0910 — APPROVED** [review]

**Comment by dishamodi0910** [comment]
@Yashgabani845 We're thrilled to inform you that your pull request has been successfully merged into the APIverse🚀🎁
Your hard work, dedication, and expertise have made a significant impact on our project, and we couldn't be more grateful for your contributions.😇
Your code will now be a part of our growing ecosystem, helping developers worldwide to create exceptional APIs.❣️🔥
Happy Coding! ✨
Will See you soon❣️

**Comment by Yashgabani845** [comment]
@dishamodi0910  you forgot to add gssoc label 
please give it otherwise my contribution won't be counted

**Pull request merged**
