### PR TITLE
[New API] : School & College Api

### LINKED ISSUE #337: [New API] : `School & College` Api
### Brief Description 🤓

- Create a `School & college` Api review and rating .
- please assign me.

### How will you develop it?🤩

-  This REST API provides ratings for schools and colleges. Users can search for institutions, submit ratings, and view aggregated ratings. The API supports CRUD operations for managing institution data and user feedback.

### Deployment

No

### Select the open source program you are contributing to

Other

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) of this project.

### PR DESCRIPTION
**Pull request by sivaprasath2004**
# 🎯 Title and Issue Number

### Closes #337 

[New API] : School & College Api

# 🗒️ Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x]  I have gone through `rules of when PR will get merged.` 
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have followed proper file structure.
- [x] I have gone through [CONTRIBUTING GUIDELINES.md](../blob/master/CONTRIBUTING.md).

# Output

Screenshot from 2024-07-22 08-15-14

Screenshot from 2024-07-22 08-14-51

Screenshot from 2024-07-22 08-15-04

Screenshot from 2024-07-22 08-14-21

 Thank you for contributing!❤️ 

Don't forget to show some love by ⭐ the repository!

### CODE REVIEW

**Comment by dishamodi0910** [comment]
Hey @sivaprasath2004, Thank you for creating PR! We will review it super soon. 😇❣️
As we continue to evolve and innovate, we encourage you to share your ideas, feedback, and code to help us push the boundaries of what's possible in the world of APIs🚀.
We hope you have followed [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md).
Thank you for being an essential part of our community. Together, we'll keep building amazing things!
Don’t forget to ⭐ our repository!
Happy Coding!✨
Will See you soon❣️

**Comment by sivaprasath2004** [comment]
@dishamodi0910 ,please merge this..

**Comment by sivaprasath2004** [comment]
@dishamodi0910 please merge this...

**Comment by sivaprasath2004** [comment]
@dishamodi0910 please assign me..

**Comment by sivaprasath2004** [comment]
@dishamodi0910 kindly merge the pr

**Review by Kritika30032002 — APPROVED** [review]

**Comment by dishamodi0910** [comment]
@sivaprasath2004 We're thrilled to inform you that your pull request has been successfully merged into the APIverse🚀🎁
Your hard work, dedication, and expertise have made a significant impact on our project, and we couldn't be more grateful for your contributions.😇
Your code will now be a part of our growing ecosystem, helping developers worldwide to create exceptional APIs.❣️🔥
Happy Coding! ✨
Will See you soon❣️

**Pull request merged**
