### PR TITLE
Added Anime API

### LINKED ISSUE #281: [Existing API Name] : Anime Api
### Brief Description 🤓

The Jikan API endpoint `https://api.jikan.moe/v4/anime?q=${query}` lets you search for anime by a query string, returning detailed information such as titles, descriptions, and genres. Replace `${query}` with your search term to get relevant results. The data is provided in JSON format for easy integration.

### Provide reference!

https://api.jikan.moe/v4/anime?q=${query}

### Select the open source program you are contributing to

Other

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) of this project.

### PR DESCRIPTION
**Pull request by tanyagupta01**
# 🎯 Anime API (Issue No. 281)

### Closes #281 

# 🗒️ Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x]  I have gone through `rules of when PR will get merged.` 
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have followed proper file structure.
- [x] I have gone through [CONTRIBUTING GUIDELINES.md](../blob/master/CONTRIBUTING.md).

Screenshot 2024-06-14 at 10 19 51 PM
Screenshot 2024-06-14 at 10 20 20 PM

### CODE REVIEW

**Comment by dishamodi0910** [comment]
Hey @tanyagupta01, Thank you for creating PR! We will review it super soon. 😇❣️
As we continue to evolve and innovate, we encourage you to share your ideas, feedback, and code to help us push the boundaries of what's possible in the world of APIs🚀.
We hope you have followed [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md).
Thank you for being an essential part of our community. Together, we'll keep building amazing things!
Don’t forget to ⭐ our repository!
Happy Coding!✨
Will See you soon❣️

**Comment by dishamodi0910** [comment]
@tanyagupta01 
image
index.html is empty file.

**Comment by dishamodi0910** [comment]
@tanyagupta01 ,I wanted to reach out and let you know that we have decided to close your pull request.🙇

In case of any issues, you can contact us on [Discord](https://discord.gg/mv4NTzN).
Thank you! ❣️
Happy Coding! ✨
Will See you soon❣️

**Comment by tanyagupta01** [comment]
@dishamodi0910 please reopen this. I will add the index.html file. This was a mistake. 
I will make another commit adding the index.html file.

**Pull request closed without merging**
