### PR TITLE
APOD API

### PR DESCRIPTION
**Pull request by UtkarshBirla28**
APOD API integration you can get any Astronomy Picture of the Day you just have to mention year, month and day in YYYY-MM-DD format
Screenshot (105)

### CODE REVIEW

**Comment by dishamodi0910** [comment]
Hey @UtkarshBirla28, Thank you for creating PR! We will review it super soon. 😇❣️
As we continue to evolve and innovate, we encourage you to share your ideas, feedback, and code to help us push the boundaries of what's possible in the world of APIs🚀.
We hope you have followed [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md).
Thank you for being an essential part of our community. Together, we'll keep building amazing things!
Don’t forget to ⭐ our repository!
Happy Coding!✨
Will See you soon❣️

**Comment by UtkarshBirla28** [comment]
@dishamodi0910    My issue number is : #308

**Comment by dishamodi0910** [comment]
Hey @UtkarshBirla28, Please do not expose your API key, you can mention in README.md about from where to generate the API key, but don't mention about that. 
It's not the good practice. Please create new PR after removing it, closing this one.

**Comment by dishamodi0910** [comment]
@UtkarshBirla28 ,I wanted to reach out and let you know that we have decided to close your pull request.🙇

In case of any issues, you can contact us on [Discord](https://discord.gg/mv4NTzN).
Thank you! ❣️
Happy Coding! ✨
Will See you soon❣️

**Pull request closed without merging**
