### PR TITLE
added weather fetching api

### LINKED ISSUE #259: [Existing API Name] : Wetather fetching api
### Brief Description 🤓

Fetch the current weather of any place using OpenWeatherMap api. please assign this to me under gssoc.

### Provide reference!

.

### Select the open source program you are contributing to

Other

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) of this project.

### PR DESCRIPTION
**Pull request by kashnx**
# 🎯 Title and Issue Number

It can fetch weather of all cities and countries.
### Closes #259 

# 🗒️ Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x]  I have gone through `rules of when PR will get merged.` 
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have followed proper file structure.
- [x] I have gone through [CONTRIBUTING GUIDELINES.md](../blob/master/CONTRIBUTING.md).

 Thank you for contributing!❤️ 

Don't forget to show some love by ⭐ the repository!

### CODE REVIEW

**Comment by dishamodi0910** [comment]
Hey @kashnx, Thank you for creating PR! We will review it super soon. 😇❣️
As we continue to evolve and innovate, we encourage you to share your ideas, feedback, and code to help us push the boundaries of what's possible in the world of APIs🚀.
We hope you have followed [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md).
Thank you for being an essential part of our community. Together, we'll keep building amazing things!
Don’t forget to ⭐ our repository!
Happy Coding!✨
Will See you soon❣️

**Comment by dishamodi0910** [comment]
@kashnx Please add appid in .env file and use from there, do not expose your credentials.

**Comment by kashnx** [comment]
making pr again

**Comment by kashnx** [comment]
https://github.com/dishamodi0910/APIVerse/pull/304 kindly check my latest pr.

**Comment by dishamodi0910** [comment]
@kashnx ,I wanted to reach out and let you know that we have decided to close your pull request.🙇

In case of any issues, you can contact us on [Discord](https://discord.gg/mv4NTzN).
Thank you! ❣️
Happy Coding! ✨
Will See you soon❣️

**Pull request closed without merging**
