### PR TITLE
[New API] : Quiz Api Added

### LINKED ISSUE #295: [New API] : Quiz Api
### Brief Description 🤓

- In this `Api` was `Random` or `specific`  category questions can be response.
-  please assign me ..
- I will work on it..

### How will you develop it?🤩

- I will develop to `node` & `Express` .

### Deployment

No

### Select the open source program you are contributing to

Other

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) of this project.

### PR DESCRIPTION
**Pull request by sivaprasath2004**
# 🎯 Title and Issue Number

[New API] : Quiz Api Added

### **ScreeenShot**

Screenshot from 2024-06-18 11-23-54

# 🗒️ Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x]  I have gone through `rules of when PR will get merged.` 
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have followed proper file structure.
- [x] I have gone through [CONTRIBUTING GUIDELINES.md](../blob/master/CONTRIBUTING.md).

 Thank you for contributing!❤️ 

Don't forget to show some love by ⭐ the repository!

### CODE REVIEW

**Comment by dishamodi0910** [comment]
Hey @sivaprasath2004, Thank you for creating PR! We will review it super soon. 😇❣️
As we continue to evolve and innovate, we encourage you to share your ideas, feedback, and code to help us push the boundaries of what's possible in the world of APIs🚀.
We hope you have followed [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md).
Thank you for being an essential part of our community. Together, we'll keep building amazing things!
Don’t forget to ⭐ our repository!
Happy Coding!✨
Will See you soon❣️

**Comment by dishamodi0910** [comment]
@sivaprasath2004 Majority of values are going hardcoded, please try to have integration with db,so someone going through code can know how to utilise it properly.

**Comment by dishamodi0910** [comment]
@sivaprasath2004 Please make changes so I can merge the PR under level 3.

**Comment by sivaprasath2004** [comment]
@dishamodi0910 i will finish it..

**Comment by sivaprasath2004** [comment]
@dishamodi0910 please i will finish it..

**Comment by sivaprasath2004** [comment]
@dishamodi0910 please merge this

**Comment by dishamodi0910** [comment]
@sivaprasath2004 We're thrilled to inform you that your pull request has been successfully merged into the APIverse🚀🎁
Your hard work, dedication, and expertise have made a significant impact on our project, and we couldn't be more grateful for your contributions.😇
Your code will now be a part of our growing ecosystem, helping developers worldwide to create exceptional APIs.❣️🔥
Happy Coding! ✨
Will See you soon❣️

**Pull request merged**
