### PR TITLE
Added new API CMS API

### LINKED ISSUE #83: [New API] : CMS API
### Brief Description 🤓

This api will be used to create a Content Management System( CMS ) , where users can create their own tables on just a click by choosing the datatype and also the field names and then they will be able to manage their own portal. 

### How will you develop it?🤩

I will use postgreSQL as database and node express for serving the backend, users will be able to do CRUD operations on their respective tables .

### Deployment

No

### Select the open source program you are contributing to

Other

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) of this project.

### PR DESCRIPTION
**Pull request by pspriyanshu601**
# 🎯[New API] : CMS API issue #83 

### Closes #83 

# 🗒️ Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x]  I have gone through `rules of when PR will get merged.` 
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have followed proper file structure.
- [x] I have gone through [CONTRIBUTING GUIDELINES.md](../blob/master/CONTRIBUTING.md).

 Thank you for contributing!❤️ 

Don't forget to show some love by ⭐ the repository!

### CODE REVIEW

**Comment by dishamodi0910** [comment]
Hey @pspriyanshu601, Thank you for creating PR! We will review it super soon. 😇❣️
As we continue to evolve and innovate, we encourage you to share your ideas, feedback, and code to help us push the boundaries of what's possible in the world of APIs🚀.
We hope you have followed [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md).
Thank you for being an essential part of our community. Together, we'll keep building amazing things!
Don’t forget to ⭐ our repository!
Happy Coding!✨
Will See you soon❣️

**Review by dishamodi0910 — CHANGES_REQUESTED** [review]
@pspriyanshu601 Please squash all your commits into single commit.

**Comment by pspriyanshu601** [comment]
@dishamodi0910 I have squashed all the commits into one commit , please review.

**Comment by pspriyanshu601** [comment]
@dishamodi0910 please review soon !!

**Review by dishamodi0910 — APPROVED** [review]

**Comment by dishamodi0910** [comment]
@pspriyanshu601 We're thrilled to inform you that your pull request has been successfully merged into the APIverse🚀🎁
Your hard work, dedication, and expertise have made a significant impact on our project, and we couldn't be more grateful for your contributions.😇
Your code will now be a part of our growing ecosystem, helping developers worldwide to create exceptional APIs.❣️🔥
Happy Coding! ✨
Will See you soon❣️

**Comment by pspriyanshu601** [comment]
Thanks for merging 😁.

**Comment by pspriyanshu601** [comment]
Hey ! @dishamodi0910 please add the label of gssoc to this pr else it wont be counted in gssoc.
I hope you understand .

**Comment by pspriyanshu601** [comment]
> Hey ! @dishamodi0910 please add the label of gssoc to this pr else it wont be counted in gssoc. I hope you understand .

@dishamodi0910 please see this

**Comment by pspriyanshu601** [comment]
@dishamodi0910 this pr is not showing in my page in gssoc, please its a humble request please, add the label gssoc, else it wont be counted in the gssoc24. 🥹

**Comment by pspriyanshu601** [comment]
@dishamodi0910 please seeee this , please otherwise my hardwork will be wasted

**Pull request merged**
