### PR TITLE
result-marks api with more features

### LINKED ISSUE #160: [New API] : Result marks Api
### Brief Description 🤓

As you closed my previous issue and told to add some more features like particular studnt marks,etc
so that you can give level 3 label 
in PR : #140 
and i can not work on closed issue so this issue is adding more advanced functionalities 

### How will you develop it?🤩

Reuslt Marks API
with 2roles
student role and treacher Role
Crud operation with marks and student as well.

### Deployment

None

### Select the open source program you are contributing to

Other

### Code of Conduct

- [X] I follow [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md) of this project.

### PR DESCRIPTION
**Pull request by Yashgabani845**
# 🎯 Title and Issue Number

As you told me to add 2/3 more functionalities to my result marks api in my PR: #140 
so that you can add label of level 3
As you have closed that PR,issue So i created new PR and  new Issue

###  i have added 4 new functions
 

 1. Generate Percentage of Particular Student
 2. Result of Particular Student
 3. Particular Subject marks of a Student 
 4. Get all marks of 1 Subject

 
 I hope it is 

### Closes #160 

# 🗒️ Checklist:

- [x] I have mentioned the issue number in my Pull Request.
- [x]  I have gone through `rules of when PR will get merged.` 
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have created a helpful and easy to understand `README.md`
- [x] I have followed proper file structure.
- [x] I have gone through [CONTRIBUTING GUIDELINES.md](../blob/master/CONTRIBUTING.md).

 Thank you for contributing!❤️ 

Don't forget to show some love by ⭐ the repository!

### CODE REVIEW

**Comment by dishamodi0910** [comment]
Hey @Yashgabani845, Thank you for creating PR! We will review it super soon. 😇❣️
As we continue to evolve and innovate, we encourage you to share your ideas, feedback, and code to help us push the boundaries of what's possible in the world of APIs🚀.
We hope you have followed [CONTRIBUTING GUIDELINES](../blob/master/CONTRIBUTING.md).
Thank you for being an essential part of our community. Together, we'll keep building amazing things!
Don’t forget to ⭐ our repository!
Happy Coding!✨
Will See you soon❣️

**Comment by dishamodi0910** [comment]
@Yashgabani845 Please locate package.json at proper place in directory, it's currently under models folder which shouldn't happen.

**Comment by Yashgabani845** [comment]
@dishamodi0910 i have changed location of it

**Comment by dishamodi0910** [comment]
@Yashgabani845 Good to go!🎉

**Comment by dishamodi0910** [comment]
@Yashgabani845 We're thrilled to inform you that your pull request has been successfully merged into the APIverse🚀🎁
Your hard work, dedication, and expertise have made a significant impact on our project, and we couldn't be more grateful for your contributions.😇
Your code will now be a part of our growing ecosystem, helping developers worldwide to create exceptional APIs.❣️🔥
Happy Coding! ✨
Will See you soon❣️

**Pull request merged**
